# Auto-generated router-visible netlist
# No optimal metadata included

data = {   'grid_size': 100,
    'nets': {   'NET_0': {   'length': 99,
                             'pins': [(1, 0), (1, 99)],
                             'type': 'MEDIUM'},
                'NET_1': {   'length': 99,
                             'pins': [(2, 0), (2, 99)],
                             'type': 'MEDIUM'},
                'NET_10': {   'length': 99,
                              'pins': [(11, 0), (11, 99)],
                              'type': 'MEDIUM'},
                'NET_11': {   'length': 99,
                              'pins': [(12, 0), (12, 99)],
                              'type': 'MEDIUM'},
                'NET_12': {   'length': 99,
                              'pins': [(13, 0), (13, 99)],
                              'type': 'MEDIUM'},
                'NET_13': {   'length': 99,
                              'pins': [(14, 0), (14, 99)],
                              'type': 'MEDIUM'},
                'NET_14': {   'length': 99,
                              'pins': [(15, 0), (15, 99)],
                              'type': 'MEDIUM'},
                'NET_15': {   'length': 99,
                              'pins': [(16, 0), (16, 99)],
                              'type': 'MEDIUM'},
                'NET_16': {   'length': 99,
                              'pins': [(17, 0), (17, 99)],
                              'type': 'MEDIUM'},
                'NET_17': {   'length': 99,
                              'pins': [(18, 0), (18, 99)],
                              'type': 'MEDIUM'},
                'NET_18': {   'length': 99,
                              'pins': [(19, 0), (19, 99)],
                              'type': 'MEDIUM'},
                'NET_19': {   'length': 99,
                              'pins': [(20, 0), (20, 99)],
                              'type': 'MEDIUM'},
                'NET_2': {   'length': 99,
                             'pins': [(3, 0), (3, 99)],
                             'type': 'MEDIUM'},
                'NET_20': {   'length': 99,
                              'pins': [(21, 0), (21, 99)],
                              'type': 'MEDIUM'},
                'NET_21': {   'length': 99,
                              'pins': [(22, 0), (22, 99)],
                              'type': 'MEDIUM'},
                'NET_22': {   'length': 99,
                              'pins': [(23, 0), (23, 99)],
                              'type': 'MEDIUM'},
                'NET_23': {   'length': 99,
                              'pins': [(24, 0), (24, 99)],
                              'type': 'MEDIUM'},
                'NET_24': {   'length': 99,
                              'pins': [(25, 0), (25, 99)],
                              'type': 'MEDIUM'},
                'NET_25': {   'length': 99,
                              'pins': [(26, 0), (26, 99)],
                              'type': 'MEDIUM'},
                'NET_26': {   'length': 99,
                              'pins': [(27, 0), (27, 99)],
                              'type': 'MEDIUM'},
                'NET_27': {   'length': 99,
                              'pins': [(28, 0), (28, 99)],
                              'type': 'MEDIUM'},
                'NET_28': {   'length': 99,
                              'pins': [(29, 0), (29, 99)],
                              'type': 'MEDIUM'},
                'NET_29': {   'length': 99,
                              'pins': [(30, 0), (30, 99)],
                              'type': 'MEDIUM'},
                'NET_3': {   'length': 99,
                             'pins': [(4, 0), (4, 99)],
                             'type': 'MEDIUM'},
                'NET_30': {   'length': 99,
                              'pins': [(31, 0), (31, 99)],
                              'type': 'MEDIUM'},
                'NET_31': {   'length': 99,
                              'pins': [(32, 0), (32, 99)],
                              'type': 'MEDIUM'},
                'NET_32': {   'length': 99,
                              'pins': [(33, 0), (33, 99)],
                              'type': 'MEDIUM'},
                'NET_33': {   'length': 99,
                              'pins': [(34, 0), (34, 99)],
                              'type': 'MEDIUM'},
                'NET_34': {   'length': 99,
                              'pins': [(35, 0), (35, 99)],
                              'type': 'MEDIUM'},
                'NET_35': {   'length': 99,
                              'pins': [(36, 0), (36, 99)],
                              'type': 'MEDIUM'},
                'NET_36': {   'length': 99,
                              'pins': [(37, 0), (37, 99)],
                              'type': 'MEDIUM'},
                'NET_37': {   'length': 99,
                              'pins': [(38, 0), (38, 99)],
                              'type': 'MEDIUM'},
                'NET_38': {   'length': 99,
                              'pins': [(39, 0), (39, 99)],
                              'type': 'MEDIUM'},
                'NET_39': {   'length': 99,
                              'pins': [(40, 0), (40, 99)],
                              'type': 'MEDIUM'},
                'NET_4': {   'length': 99,
                             'pins': [(5, 0), (5, 99)],
                             'type': 'MEDIUM'},
                'NET_40': {   'length': 99,
                              'pins': [(41, 0), (41, 99)],
                              'type': 'MEDIUM'},
                'NET_41': {   'length': 99,
                              'pins': [(42, 0), (42, 99)],
                              'type': 'MEDIUM'},
                'NET_42': {   'length': 99,
                              'pins': [(43, 0), (43, 99)],
                              'type': 'MEDIUM'},
                'NET_43': {   'length': 99,
                              'pins': [(44, 0), (44, 99)],
                              'type': 'MEDIUM'},
                'NET_44': {   'length': 99,
                              'pins': [(45, 0), (45, 99)],
                              'type': 'MEDIUM'},
                'NET_45': {   'length': 99,
                              'pins': [(46, 0), (46, 99)],
                              'type': 'MEDIUM'},
                'NET_46': {   'length': 99,
                              'pins': [(47, 0), (47, 99)],
                              'type': 'MEDIUM'},
                'NET_47': {   'length': 99,
                              'pins': [(48, 0), (48, 99)],
                              'type': 'MEDIUM'},
                'NET_48': {   'length': 99,
                              'pins': [(49, 0), (49, 99)],
                              'type': 'MEDIUM'},
                'NET_49': {   'length': 99,
                              'pins': [(50, 0), (50, 99)],
                              'type': 'MEDIUM'},
                'NET_5': {   'length': 99,
                             'pins': [(6, 0), (6, 99)],
                             'type': 'MEDIUM'},
                'NET_50': {   'length': 99,
                              'pins': [(0, 1), (99, 1)],
                              'type': 'MEDIUM'},
                'NET_51': {   'length': 99,
                              'pins': [(0, 2), (99, 2)],
                              'type': 'MEDIUM'},
                'NET_52': {   'length': 99,
                              'pins': [(0, 3), (99, 3)],
                              'type': 'MEDIUM'},
                'NET_53': {   'length': 99,
                              'pins': [(0, 4), (99, 4)],
                              'type': 'MEDIUM'},
                'NET_54': {   'length': 99,
                              'pins': [(0, 5), (99, 5)],
                              'type': 'MEDIUM'},
                'NET_55': {   'length': 99,
                              'pins': [(0, 6), (99, 6)],
                              'type': 'MEDIUM'},
                'NET_56': {   'length': 99,
                              'pins': [(0, 7), (99, 7)],
                              'type': 'MEDIUM'},
                'NET_57': {   'length': 99,
                              'pins': [(0, 8), (99, 8)],
                              'type': 'MEDIUM'},
                'NET_58': {   'length': 99,
                              'pins': [(0, 9), (99, 9)],
                              'type': 'MEDIUM'},
                'NET_59': {   'length': 99,
                              'pins': [(0, 10), (99, 10)],
                              'type': 'MEDIUM'},
                'NET_6': {   'length': 99,
                             'pins': [(7, 0), (7, 99)],
                             'type': 'MEDIUM'},
                'NET_60': {   'length': 99,
                              'pins': [(0, 11), (99, 11)],
                              'type': 'MEDIUM'},
                'NET_61': {   'length': 99,
                              'pins': [(0, 12), (99, 12)],
                              'type': 'MEDIUM'},
                'NET_62': {   'length': 99,
                              'pins': [(0, 13), (99, 13)],
                              'type': 'MEDIUM'},
                'NET_63': {   'length': 99,
                              'pins': [(0, 14), (99, 14)],
                              'type': 'MEDIUM'},
                'NET_64': {   'length': 99,
                              'pins': [(0, 15), (99, 15)],
                              'type': 'MEDIUM'},
                'NET_65': {   'length': 99,
                              'pins': [(0, 16), (99, 16)],
                              'type': 'MEDIUM'},
                'NET_66': {   'length': 99,
                              'pins': [(0, 17), (99, 17)],
                              'type': 'MEDIUM'},
                'NET_67': {   'length': 99,
                              'pins': [(0, 18), (99, 18)],
                              'type': 'MEDIUM'},
                'NET_68': {   'length': 99,
                              'pins': [(0, 19), (99, 19)],
                              'type': 'MEDIUM'},
                'NET_69': {   'length': 99,
                              'pins': [(0, 20), (99, 20)],
                              'type': 'MEDIUM'},
                'NET_7': {   'length': 99,
                             'pins': [(8, 0), (8, 99)],
                             'type': 'MEDIUM'},
                'NET_70': {   'length': 99,
                              'pins': [(0, 21), (99, 21)],
                              'type': 'MEDIUM'},
                'NET_71': {   'length': 99,
                              'pins': [(0, 22), (99, 22)],
                              'type': 'MEDIUM'},
                'NET_72': {   'length': 99,
                              'pins': [(0, 23), (99, 23)],
                              'type': 'MEDIUM'},
                'NET_73': {   'length': 99,
                              'pins': [(0, 24), (99, 24)],
                              'type': 'MEDIUM'},
                'NET_74': {   'length': 99,
                              'pins': [(0, 25), (99, 25)],
                              'type': 'MEDIUM'},
                'NET_75': {   'length': 99,
                              'pins': [(0, 26), (99, 26)],
                              'type': 'MEDIUM'},
                'NET_76': {   'length': 99,
                              'pins': [(0, 27), (99, 27)],
                              'type': 'MEDIUM'},
                'NET_77': {   'length': 99,
                              'pins': [(0, 28), (99, 28)],
                              'type': 'MEDIUM'},
                'NET_78': {   'length': 99,
                              'pins': [(0, 29), (99, 29)],
                              'type': 'MEDIUM'},
                'NET_79': {   'length': 99,
                              'pins': [(0, 30), (99, 30)],
                              'type': 'MEDIUM'},
                'NET_8': {   'length': 99,
                             'pins': [(9, 0), (9, 99)],
                             'type': 'MEDIUM'},
                'NET_80': {   'length': 99,
                              'pins': [(0, 31), (99, 31)],
                              'type': 'MEDIUM'},
                'NET_81': {   'length': 99,
                              'pins': [(0, 32), (99, 32)],
                              'type': 'MEDIUM'},
                'NET_82': {   'length': 99,
                              'pins': [(0, 33), (99, 33)],
                              'type': 'MEDIUM'},
                'NET_83': {   'length': 99,
                              'pins': [(0, 34), (99, 34)],
                              'type': 'MEDIUM'},
                'NET_84': {   'length': 99,
                              'pins': [(0, 35), (99, 35)],
                              'type': 'MEDIUM'},
                'NET_85': {   'length': 99,
                              'pins': [(0, 36), (99, 36)],
                              'type': 'MEDIUM'},
                'NET_86': {   'length': 99,
                              'pins': [(0, 37), (99, 37)],
                              'type': 'MEDIUM'},
                'NET_87': {   'length': 99,
                              'pins': [(0, 38), (99, 38)],
                              'type': 'MEDIUM'},
                'NET_88': {   'length': 99,
                              'pins': [(0, 39), (99, 39)],
                              'type': 'MEDIUM'},
                'NET_89': {   'length': 99,
                              'pins': [(0, 40), (99, 40)],
                              'type': 'MEDIUM'},
                'NET_9': {   'length': 99,
                             'pins': [(10, 0), (10, 99)],
                             'type': 'MEDIUM'},
                'NET_90': {   'length': 99,
                              'pins': [(0, 41), (99, 41)],
                              'type': 'MEDIUM'},
                'NET_91': {   'length': 99,
                              'pins': [(0, 42), (99, 42)],
                              'type': 'MEDIUM'},
                'NET_92': {   'length': 99,
                              'pins': [(0, 43), (99, 43)],
                              'type': 'MEDIUM'},
                'NET_93': {   'length': 99,
                              'pins': [(0, 44), (99, 44)],
                              'type': 'MEDIUM'},
                'NET_94': {   'length': 99,
                              'pins': [(0, 45), (99, 45)],
                              'type': 'MEDIUM'},
                'NET_95': {   'length': 99,
                              'pins': [(0, 46), (99, 46)],
                              'type': 'MEDIUM'},
                'NET_96': {   'length': 99,
                              'pins': [(0, 47), (99, 47)],
                              'type': 'MEDIUM'},
                'NET_97': {   'length': 99,
                              'pins': [(0, 48), (99, 48)],
                              'type': 'MEDIUM'},
                'NET_98': {   'length': 99,
                              'pins': [(0, 49), (99, 49)],
                              'type': 'MEDIUM'},
                'NET_99': {   'length': 99,
                              'pins': [(0, 50), (99, 50)],
                              'type': 'MEDIUM'}}}
