# Auto-generated router-visible netlist
# No optimal metadata included

data = {   'grid_size': 100,
    'nets': {   'NET_0': {   'length': 3,
                             'pins': [(99, 56), (99, 59)],
                             'type': 'LOCAL'},
                'NET_1': {   'length': 12,
                             'pins': [(5, 72), (5, 60)],
                             'type': 'LOCAL'},
                'NET_10': {   'length': 17,
                              'pins': [(97, 67), (87, 74)],
                              'type': 'LOCAL'},
                'NET_100': {   'length': 17,
                               'pins': [(67, 87), (75, 96)],
                               'type': 'LOCAL'},
                'NET_101': {   'length': 11,
                               'pins': [(18, 46), (21, 38)],
                               'type': 'LOCAL'},
                'NET_102': {   'length': 7,
                               'pins': [(56, 99), (60, 96)],
                               'type': 'LOCAL'},
                'NET_103': {   'length': 19,
                               'pins': [(16, 11), (6, 20)],
                               'type': 'LOCAL'},
                'NET_104': {   'length': 12,
                               'pins': [(12, 53), (19, 48)],
                               'type': 'LOCAL'},
                'NET_105': {   'length': 8,
                               'pins': [(43, 31), (40, 36)],
                               'type': 'LOCAL'},
                'NET_106': {   'length': 19,
                               'pins': [(60, 65), (48, 72)],
                               'type': 'LOCAL'},
                'NET_107': {   'length': 15,
                               'pins': [(97, 50), (96, 64)],
                               'type': 'LOCAL'},
                'NET_108': {   'length': 13,
                               'pins': [(71, 79), (63, 84)],
                               'type': 'LOCAL'},
                'NET_109': {   'length': 19,
                               'pins': [(11, 9), (21, 18)],
                               'type': 'LOCAL'},
                'NET_11': {   'length': 8,
                              'pins': [(42, 72), (44, 66)],
                              'type': 'LOCAL'},
                'NET_110': {   'length': 14,
                               'pins': [(81, 88), (78, 99)],
                               'type': 'LOCAL'},
                'NET_111': {   'length': 11,
                               'pins': [(23, 54), (21, 63)],
                               'type': 'LOCAL'},
                'NET_112': {   'length': 14,
                               'pins': [(9, 85), (0, 90)],
                               'type': 'LOCAL'},
                'NET_113': {   'length': 13,
                               'pins': [(27, 11), (38, 9)],
                               'type': 'LOCAL'},
                'NET_114': {   'length': 6,
                               'pins': [(78, 70), (78, 76)],
                               'type': 'LOCAL'},
                'NET_115': {   'length': 3,
                               'pins': [(42, 31), (40, 30)],
                               'type': 'LOCAL'},
                'NET_116': {   'length': 15,
                               'pins': [(75, 70), (72, 82)],
                               'type': 'LOCAL'},
                'NET_117': {   'length': 5,
                               'pins': [(95, 87), (93, 90)],
                               'type': 'LOCAL'},
                'NET_118': {   'length': 15,
                               'pins': [(47, 53), (40, 45)],
                               'type': 'LOCAL'},
                'NET_119': {   'length': 10,
                               'pins': [(86, 99), (91, 94)],
                               'type': 'LOCAL'},
                'NET_12': {   'length': 4,
                              'pins': [(88, 98), (86, 96)],
                              'type': 'LOCAL'},
                'NET_120': {   'length': 13,
                               'pins': [(16, 99), (23, 93)],
                               'type': 'LOCAL'},
                'NET_121': {   'length': 20,
                               'pins': [(7, 55), (2, 40)],
                               'type': 'LOCAL'},
                'NET_122': {   'length': 11,
                               'pins': [(8, 17), (3, 11)],
                               'type': 'LOCAL'},
                'NET_123': {   'length': 17,
                               'pins': [(13, 39), (25, 34)],
                               'type': 'LOCAL'},
                'NET_124': {   'length': 16,
                               'pins': [(7, 37), (11, 25)],
                               'type': 'LOCAL'},
                'NET_125': {   'length': 11,
                               'pins': [(9, 42), (18, 44)],
                               'type': 'LOCAL'},
                'NET_126': {   'length': 16,
                               'pins': [(4, 21), (6, 35)],
                               'type': 'LOCAL'},
                'NET_127': {   'length': 15,
                               'pins': [(79, 77), (64, 77)],
                               'type': 'LOCAL'},
                'NET_128': {   'length': 6,
                               'pins': [(58, 75), (59, 70)],
                               'type': 'LOCAL'},
                'NET_129': {   'length': 16,
                               'pins': [(31, 47), (23, 55)],
                               'type': 'LOCAL'},
                'NET_13': {   'length': 9,
                              'pins': [(83, 30), (82, 22)],
                              'type': 'LOCAL'},
                'NET_130': {   'length': 18,
                               'pins': [(37, 44), (23, 48)],
                               'type': 'LOCAL'},
                'NET_131': {   'length': 11,
                               'pins': [(18, 17), (12, 12)],
                               'type': 'LOCAL'},
                'NET_132': {   'length': 10,
                               'pins': [(79, 15), (84, 20)],
                               'type': 'LOCAL'},
                'NET_133': {   'length': 19,
                               'pins': [(57, 72), (74, 74)],
                               'type': 'LOCAL'},
                'NET_134': {   'length': 15,
                               'pins': [(11, 64), (0, 68)],
                               'type': 'LOCAL'},
                'NET_135': {   'length': 12,
                               'pins': [(28, 18), (17, 19)],
                               'type': 'LOCAL'},
                'NET_136': {   'length': 6,
                               'pins': [(90, 44), (90, 38)],
                               'type': 'LOCAL'},
                'NET_137': {   'length': 20,
                               'pins': [(38, 52), (48, 62)],
                               'type': 'LOCAL'},
                'NET_138': {   'length': 20,
                               'pins': [(6, 55), (20, 61)],
                               'type': 'LOCAL'},
                'NET_139': {   'length': 8,
                               'pins': [(9, 16), (13, 12)],
                               'type': 'LOCAL'},
                'NET_14': {   'length': 15,
                              'pins': [(58, 21), (56, 34)],
                              'type': 'LOCAL'},
                'NET_140': {   'length': 15,
                               'pins': [(81, 90), (91, 95)],
                               'type': 'LOCAL'},
                'NET_141': {   'length': 5,
                               'pins': [(14, 79), (12, 82)],
                               'type': 'LOCAL'},
                'NET_142': {   'length': 16,
                               'pins': [(31, 58), (29, 44)],
                               'type': 'LOCAL'},
                'NET_143': {   'length': 14,
                               'pins': [(47, 64), (54, 57)],
                               'type': 'LOCAL'},
                'NET_144': {   'length': 20,
                               'pins': [(52, 74), (42, 64)],
                               'type': 'LOCAL'},
                'NET_145': {   'length': 19,
                               'pins': [(53, 16), (58, 2)],
                               'type': 'LOCAL'},
                'NET_146': {   'length': 10,
                               'pins': [(71, 20), (75, 14)],
                               'type': 'LOCAL'},
                'NET_147': {   'length': 18,
                               'pins': [(58, 52), (41, 53)],
                               'type': 'LOCAL'},
                'NET_148': {   'length': 20,
                               'pins': [(37, 39), (43, 25)],
                               'type': 'LOCAL'},
                'NET_149': {   'length': 18,
                               'pins': [(59, 0), (54, 13)],
                               'type': 'LOCAL'},
                'NET_15': {   'length': 15,
                              'pins': [(93, 22), (98, 32)],
                              'type': 'LOCAL'},
                'NET_150': {   'length': 14,
                               'pins': [(32, 8), (25, 1)],
                               'type': 'LOCAL'},
                'NET_151': {   'length': 8,
                               'pins': [(26, 48), (18, 48)],
                               'type': 'LOCAL'},
                'NET_152': {   'length': 3,
                               'pins': [(49, 93), (52, 93)],
                               'type': 'LOCAL'},
                'NET_153': {   'length': 20,
                               'pins': [(1, 36), (1, 56)],
                               'type': 'LOCAL'},
                'NET_154': {   'length': 16,
                               'pins': [(73, 32), (80, 41)],
                               'type': 'LOCAL'},
                'NET_155': {   'length': 3,
                               'pins': [(5, 81), (7, 82)],
                               'type': 'LOCAL'},
                'NET_156': {   'length': 14,
                               'pins': [(81, 93), (70, 90)],
                               'type': 'LOCAL'},
                'NET_157': {   'length': 14,
                               'pins': [(97, 85), (84, 84)],
                               'type': 'LOCAL'},
                'NET_158': {   'length': 13,
                               'pins': [(37, 68), (46, 64)],
                               'type': 'LOCAL'},
                'NET_159': {   'length': 8,
                               'pins': [(62, 18), (68, 20)],
                               'type': 'LOCAL'},
                'NET_16': {   'length': 20,
                              'pins': [(30, 89), (22, 77)],
                              'type': 'LOCAL'},
                'NET_160': {   'length': 6,
                               'pins': [(76, 62), (82, 62)],
                               'type': 'LOCAL'},
                'NET_161': {   'length': 17,
                               'pins': [(3, 65), (2, 49)],
                               'type': 'LOCAL'},
                'NET_162': {   'length': 12,
                               'pins': [(88, 11), (95, 16)],
                               'type': 'LOCAL'},
                'NET_163': {   'length': 20,
                               'pins': [(32, 71), (25, 58)],
                               'type': 'LOCAL'},
                'NET_164': {   'length': 9,
                               'pins': [(12, 63), (15, 57)],
                               'type': 'LOCAL'},
                'NET_165': {   'length': 10,
                               'pins': [(17, 42), (7, 42)],
                               'type': 'LOCAL'},
                'NET_166': {   'length': 9,
                               'pins': [(62, 59), (59, 53)],
                               'type': 'LOCAL'},
                'NET_167': {   'length': 11,
                               'pins': [(98, 92), (90, 89)],
                               'type': 'LOCAL'},
                'NET_168': {   'length': 6,
                               'pins': [(23, 85), (25, 89)],
                               'type': 'LOCAL'},
                'NET_169': {   'length': 6,
                               'pins': [(39, 92), (35, 94)],
                               'type': 'LOCAL'},
                'NET_17': {   'length': 18,
                              'pins': [(42, 22), (48, 34)],
                              'type': 'LOCAL'},
                'NET_170': {   'length': 17,
                               'pins': [(35, 80), (44, 88)],
                               'type': 'LOCAL'},
                'NET_171': {   'length': 15,
                               'pins': [(23, 90), (33, 85)],
                               'type': 'LOCAL'},
                'NET_172': {   'length': 12,
                               'pins': [(92, 1), (88, 9)],
                               'type': 'LOCAL'},
                'NET_173': {   'length': 11,
                               'pins': [(87, 1), (96, 3)],
                               'type': 'LOCAL'},
                'NET_174': {   'length': 12,
                               'pins': [(16, 59), (17, 48)],
                               'type': 'LOCAL'},
                'NET_175': {   'length': 9,
                               'pins': [(87, 25), (86, 33)],
                               'type': 'LOCAL'},
                'NET_176': {   'length': 8,
                               'pins': [(53, 62), (49, 58)],
                               'type': 'LOCAL'},
                'NET_177': {   'length': 20,
                               'pins': [(25, 35), (32, 48)],
                               'type': 'LOCAL'},
                'NET_178': {   'length': 15,
                               'pins': [(18, 66), (28, 71)],
                               'type': 'LOCAL'},
                'NET_179': {   'length': 6,
                               'pins': [(42, 86), (40, 90)],
                               'type': 'LOCAL'},
                'NET_18': {   'length': 17,
                              'pins': [(88, 25), (90, 40)],
                              'type': 'LOCAL'},
                'NET_180': {   'length': 12,
                               'pins': [(64, 62), (60, 70)],
                               'type': 'LOCAL'},
                'NET_181': {   'length': 18,
                               'pins': [(91, 60), (93, 44)],
                               'type': 'LOCAL'},
                'NET_182': {   'length': 5,
                               'pins': [(72, 50), (70, 47)],
                               'type': 'LOCAL'},
                'NET_183': {   'length': 16,
                               'pins': [(45, 74), (35, 68)],
                               'type': 'LOCAL'},
                'NET_184': {   'length': 5,
                               'pins': [(2, 28), (4, 31)],
                               'type': 'LOCAL'},
                'NET_185': {   'length': 20,
                               'pins': [(23, 0), (35, 8)],
                               'type': 'LOCAL'},
                'NET_186': {   'length': 18,
                               'pins': [(68, 35), (81, 40)],
                               'type': 'LOCAL'},
                'NET_187': {   'length': 14,
                               'pins': [(26, 65), (31, 56)],
                               'type': 'LOCAL'},
                'NET_188': {   'length': 14,
                               'pins': [(26, 5), (13, 6)],
                               'type': 'LOCAL'},
                'NET_189': {   'length': 16,
                               'pins': [(22, 50), (16, 60)],
                               'type': 'LOCAL'},
                'NET_19': {   'length': 14,
                              'pins': [(78, 31), (69, 26)],
                              'type': 'LOCAL'},
                'NET_190': {   'length': 20,
                               'pins': [(64, 59), (84, 59)],
                               'type': 'LOCAL'},
                'NET_191': {   'length': 16,
                               'pins': [(92, 19), (84, 11)],
                               'type': 'LOCAL'},
                'NET_192': {   'length': 13,
                               'pins': [(24, 59), (34, 62)],
                               'type': 'LOCAL'},
                'NET_193': {   'length': 12,
                               'pins': [(36, 35), (34, 25)],
                               'type': 'LOCAL'},
                'NET_194': {   'length': 7,
                               'pins': [(3, 23), (1, 18)],
                               'type': 'LOCAL'},
                'NET_195': {   'length': 18,
                               'pins': [(67, 23), (53, 27)],
                               'type': 'LOCAL'},
                'NET_196': {   'length': 9,
                               'pins': [(40, 13), (43, 7)],
                               'type': 'LOCAL'},
                'NET_197': {   'length': 9,
                               'pins': [(79, 34), (82, 28)],
                               'type': 'LOCAL'},
                'NET_198': {   'length': 20,
                               'pins': [(52, 79), (57, 94)],
                               'type': 'LOCAL'},
                'NET_199': {   'length': 20,
                               'pins': [(75, 51), (94, 52)],
                               'type': 'LOCAL'},
                'NET_2': {   'length': 17,
                             'pins': [(76, 21), (67, 13)],
                             'type': 'LOCAL'},
                'NET_20': {   'length': 12,
                              'pins': [(55, 56), (66, 57)],
                              'type': 'LOCAL'},
                'NET_200': {   'length': 10,
                               'pins': [(79, 30), (88, 29)],
                               'type': 'LOCAL'},
                'NET_201': {   'length': 18,
                               'pins': [(51, 0), (42, 9)],
                               'type': 'LOCAL'},
                'NET_202': {   'length': 12,
                               'pins': [(2, 84), (12, 86)],
                               'type': 'LOCAL'},
                'NET_203': {   'length': 18,
                               'pins': [(74, 25), (81, 36)],
                               'type': 'LOCAL'},
                'NET_204': {   'length': 17,
                               'pins': [(77, 32), (93, 33)],
                               'type': 'LOCAL'},
                'NET_205': {   'length': 10,
                               'pins': [(80, 99), (73, 96)],
                               'type': 'LOCAL'},
                'NET_206': {   'length': 15,
                               'pins': [(42, 89), (43, 75)],
                               'type': 'LOCAL'},
                'NET_207': {   'length': 6,
                               'pins': [(92, 45), (93, 40)],
                               'type': 'LOCAL'},
                'NET_208': {   'length': 11,
                               'pins': [(92, 33), (82, 32)],
                               'type': 'LOCAL'},
                'NET_209': {   'length': 4,
                               'pins': [(32, 87), (29, 86)],
                               'type': 'LOCAL'},
                'NET_21': {   'length': 10,
                              'pins': [(84, 87), (86, 79)],
                              'type': 'LOCAL'},
                'NET_210': {   'length': 10,
                               'pins': [(9, 54), (3, 58)],
                               'type': 'LOCAL'},
                'NET_211': {   'length': 2,
                               'pins': [(34, 52), (33, 51)],
                               'type': 'LOCAL'},
                'NET_212': {   'length': 10,
                               'pins': [(72, 76), (63, 77)],
                               'type': 'LOCAL'},
                'NET_213': {   'length': 15,
                               'pins': [(11, 71), (22, 67)],
                               'type': 'LOCAL'},
                'NET_214': {   'length': 8,
                               'pins': [(38, 34), (33, 37)],
                               'type': 'LOCAL'},
                'NET_215': {   'length': 5,
                               'pins': [(33, 6), (32, 2)],
                               'type': 'LOCAL'},
                'NET_216': {   'length': 13,
                               'pins': [(53, 12), (61, 7)],
                               'type': 'LOCAL'},
                'NET_217': {   'length': 20,
                               'pins': [(33, 91), (46, 84)],
                               'type': 'LOCAL'},
                'NET_218': {   'length': 13,
                               'pins': [(20, 40), (19, 28)],
                               'type': 'LOCAL'},
                'NET_219': {   'length': 18,
                               'pins': [(3, 7), (10, 18)],
                               'type': 'LOCAL'},
                'NET_22': {   'length': 18,
                              'pins': [(52, 86), (34, 86)],
                              'type': 'LOCAL'},
                'NET_220': {   'length': 19,
                               'pins': [(13, 65), (25, 72)],
                               'type': 'LOCAL'},
                'NET_221': {   'length': 7,
                               'pins': [(60, 54), (63, 50)],
                               'type': 'LOCAL'},
                'NET_222': {   'length': 9,
                               'pins': [(6, 51), (8, 58)],
                               'type': 'LOCAL'},
                'NET_223': {   'length': 8,
                               'pins': [(27, 82), (23, 86)],
                               'type': 'LOCAL'},
                'NET_224': {   'length': 14,
                               'pins': [(30, 22), (25, 13)],
                               'type': 'LOCAL'},
                'NET_225': {   'length': 19,
                               'pins': [(4, 98), (0, 83)],
                               'type': 'LOCAL'},
                'NET_226': {   'length': 18,
                               'pins': [(98, 41), (84, 45)],
                               'type': 'LOCAL'},
                'NET_227': {   'length': 13,
                               'pins': [(37, 51), (41, 60)],
                               'type': 'LOCAL'},
                'NET_228': {   'length': 20,
                               'pins': [(27, 13), (9, 11)],
                               'type': 'LOCAL'},
                'NET_229': {   'length': 14,
                               'pins': [(55, 18), (50, 27)],
                               'type': 'LOCAL'},
                'NET_23': {   'length': 13,
                              'pins': [(64, 3), (73, 7)],
                              'type': 'LOCAL'},
                'NET_230': {   'length': 15,
                               'pins': [(16, 10), (6, 15)],
                               'type': 'LOCAL'},
                'NET_231': {   'length': 20,
                               'pins': [(54, 51), (71, 48)],
                               'type': 'LOCAL'},
                'NET_232': {   'length': 2,
                               'pins': [(46, 98), (45, 97)],
                               'type': 'LOCAL'},
                'NET_233': {   'length': 14,
                               'pins': [(60, 64), (49, 61)],
                               'type': 'LOCAL'},
                'NET_234': {   'length': 20,
                               'pins': [(74, 13), (67, 0)],
                               'type': 'LOCAL'},
                'NET_235': {   'length': 12,
                               'pins': [(37, 56), (31, 62)],
                               'type': 'LOCAL'},
                'NET_236': {   'length': 18,
                               'pins': [(50, 98), (62, 92)],
                               'type': 'LOCAL'},
                'NET_237': {   'length': 14,
                               'pins': [(89, 22), (87, 34)],
                               'type': 'LOCAL'},
                'NET_238': {   'length': 16,
                               'pins': [(93, 65), (96, 52)],
                               'type': 'LOCAL'},
                'NET_239': {   'length': 14,
                               'pins': [(99, 80), (99, 94)],
                               'type': 'LOCAL'},
                'NET_24': {   'length': 17,
                              'pins': [(37, 31), (22, 33)],
                              'type': 'LOCAL'},
                'NET_240': {   'length': 19,
                               'pins': [(83, 0), (69, 5)],
                               'type': 'LOCAL'},
                'NET_241': {   'length': 3,
                               'pins': [(33, 56), (36, 56)],
                               'type': 'LOCAL'},
                'NET_242': {   'length': 13,
                               'pins': [(49, 53), (44, 45)],
                               'type': 'LOCAL'},
                'NET_243': {   'length': 3,
                               'pins': [(49, 57), (52, 57)],
                               'type': 'LOCAL'},
                'NET_244': {   'length': 17,
                               'pins': [(70, 42), (65, 54)],
                               'type': 'LOCAL'},
                'NET_245': {   'length': 14,
                               'pins': [(52, 5), (51, 18)],
                               'type': 'LOCAL'},
                'NET_246': {   'length': 7,
                               'pins': [(51, 73), (52, 67)],
                               'type': 'LOCAL'},
                'NET_247': {   'length': 10,
                               'pins': [(83, 74), (87, 68)],
                               'type': 'LOCAL'},
                'NET_248': {   'length': 9,
                               'pins': [(71, 7), (76, 11)],
                               'type': 'LOCAL'},
                'NET_249': {   'length': 12,
                               'pins': [(68, 62), (67, 51)],
                               'type': 'LOCAL'},
                'NET_25': {   'length': 19,
                              'pins': [(20, 53), (2, 54)],
                              'type': 'LOCAL'},
                'NET_250': {   'length': 12,
                               'pins': [(36, 88), (31, 81)],
                               'type': 'LOCAL'},
                'NET_251': {   'length': 15,
                               'pins': [(48, 17), (47, 31)],
                               'type': 'LOCAL'},
                'NET_252': {   'length': 11,
                               'pins': [(50, 33), (50, 44)],
                               'type': 'LOCAL'},
                'NET_253': {   'length': 12,
                               'pins': [(67, 81), (59, 77)],
                               'type': 'LOCAL'},
                'NET_254': {   'length': 19,
                               'pins': [(98, 80), (95, 96)],
                               'type': 'LOCAL'},
                'NET_255': {   'length': 19,
                               'pins': [(33, 20), (28, 6)],
                               'type': 'LOCAL'},
                'NET_256': {   'length': 20,
                               'pins': [(41, 52), (48, 39)],
                               'type': 'LOCAL'},
                'NET_257': {   'length': 10,
                               'pins': [(61, 64), (65, 58)],
                               'type': 'LOCAL'},
                'NET_258': {   'length': 14,
                               'pins': [(88, 48), (86, 36)],
                               'type': 'LOCAL'},
                'NET_259': {   'length': 12,
                               'pins': [(59, 38), (64, 45)],
                               'type': 'LOCAL'},
                'NET_26': {   'length': 13,
                              'pins': [(20, 55), (12, 50)],
                              'type': 'LOCAL'},
                'NET_260': {   'length': 11,
                               'pins': [(33, 33), (40, 37)],
                               'type': 'LOCAL'},
                'NET_261': {   'length': 6,
                               'pins': [(53, 1), (57, 3)],
                               'type': 'LOCAL'},
                'NET_262': {   'length': 4,
                               'pins': [(27, 26), (31, 26)],
                               'type': 'LOCAL'},
                'NET_263': {   'length': 10,
                               'pins': [(47, 59), (47, 49)],
                               'type': 'LOCAL'},
                'NET_264': {   'length': 12,
                               'pins': [(89, 53), (77, 53)],
                               'type': 'LOCAL'},
                'NET_265': {   'length': 9,
                               'pins': [(71, 77), (77, 74)],
                               'type': 'LOCAL'},
                'NET_266': {   'length': 15,
                               'pins': [(94, 46), (85, 40)],
                               'type': 'LOCAL'},
                'NET_267': {   'length': 13,
                               'pins': [(21, 75), (17, 84)],
                               'type': 'LOCAL'},
                'NET_268': {   'length': 6,
                               'pins': [(13, 70), (11, 74)],
                               'type': 'LOCAL'},
                'NET_269': {   'length': 7,
                               'pins': [(58, 6), (58, 13)],
                               'type': 'LOCAL'},
                'NET_27': {   'length': 12,
                              'pins': [(11, 40), (5, 34)],
                              'type': 'LOCAL'},
                'NET_270': {   'length': 16,
                               'pins': [(69, 73), (83, 71)],
                               'type': 'LOCAL'},
                'NET_271': {   'length': 16,
                               'pins': [(25, 63), (9, 63)],
                               'type': 'LOCAL'},
                'NET_272': {   'length': 11,
                               'pins': [(81, 42), (87, 37)],
                               'type': 'LOCAL'},
                'NET_273': {   'length': 19,
                               'pins': [(83, 78), (86, 94)],
                               'type': 'LOCAL'},
                'NET_274': {   'length': 13,
                               'pins': [(19, 73), (28, 77)],
                               'type': 'LOCAL'},
                'NET_275': {   'length': 13,
                               'pins': [(56, 24), (54, 35)],
                               'type': 'LOCAL'},
                'NET_276': {   'length': 20,
                               'pins': [(77, 45), (83, 59)],
                               'type': 'LOCAL'},
                'NET_277': {   'length': 15,
                               'pins': [(54, 20), (67, 18)],
                               'type': 'LOCAL'},
                'NET_278': {   'length': 16,
                               'pins': [(83, 61), (87, 49)],
                               'type': 'LOCAL'},
                'NET_279': {   'length': 20,
                               'pins': [(66, 84), (86, 84)],
                               'type': 'LOCAL'},
                'NET_28': {   'length': 17,
                              'pins': [(64, 86), (74, 79)],
                              'type': 'LOCAL'},
                'NET_280': {   'length': 10,
                               'pins': [(74, 28), (78, 34)],
                               'type': 'LOCAL'},
                'NET_281': {   'length': 17,
                               'pins': [(2, 73), (11, 65)],
                               'type': 'LOCAL'},
                'NET_282': {   'length': 15,
                               'pins': [(24, 52), (34, 57)],
                               'type': 'LOCAL'},
                'NET_283': {   'length': 4,
                               'pins': [(53, 75), (52, 78)],
                               'type': 'LOCAL'},
                'NET_284': {   'length': 19,
                               'pins': [(99, 29), (94, 43)],
                               'type': 'LOCAL'},
                'NET_285': {   'length': 19,
                               'pins': [(79, 26), (70, 36)],
                               'type': 'LOCAL'},
                'NET_286': {   'length': 19,
                               'pins': [(26, 47), (45, 47)],
                               'type': 'LOCAL'},
                'NET_287': {   'length': 19,
                               'pins': [(84, 63), (71, 69)],
                               'type': 'LOCAL'},
                'NET_288': {   'length': 19,
                               'pins': [(15, 1), (15, 20)],
                               'type': 'LOCAL'},
                'NET_289': {   'length': 15,
                               'pins': [(62, 25), (57, 35)],
                               'type': 'LOCAL'},
                'NET_29': {   'length': 15,
                              'pins': [(4, 84), (15, 80)],
                              'type': 'LOCAL'},
                'NET_290': {   'length': 16,
                               'pins': [(51, 54), (55, 66)],
                               'type': 'LOCAL'},
                'NET_291': {   'length': 14,
                               'pins': [(8, 29), (10, 17)],
                               'type': 'LOCAL'},
                'NET_292': {   'length': 15,
                               'pins': [(63, 99), (71, 92)],
                               'type': 'LOCAL'},
                'NET_293': {   'length': 18,
                               'pins': [(12, 28), (28, 26)],
                               'type': 'LOCAL'},
                'NET_294': {   'length': 16,
                               'pins': [(88, 40), (89, 55)],
                               'type': 'LOCAL'},
                'NET_295': {   'length': 15,
                               'pins': [(76, 65), (83, 73)],
                               'type': 'LOCAL'},
                'NET_296': {   'length': 11,
                               'pins': [(3, 9), (7, 2)],
                               'type': 'LOCAL'},
                'NET_297': {   'length': 13,
                               'pins': [(32, 92), (38, 99)],
                               'type': 'LOCAL'},
                'NET_298': {   'length': 14,
                               'pins': [(39, 4), (50, 7)],
                               'type': 'LOCAL'},
                'NET_299': {   'length': 17,
                               'pins': [(33, 95), (44, 89)],
                               'type': 'LOCAL'},
                'NET_3': {   'length': 20,
                             'pins': [(62, 48), (64, 30)],
                             'type': 'LOCAL'},
                'NET_30': {   'length': 9,
                              'pins': [(95, 21), (99, 26)],
                              'type': 'LOCAL'},
                'NET_300': {   'length': 16,
                               'pins': [(66, 25), (58, 17)],
                               'type': 'LOCAL'},
                'NET_301': {   'length': 6,
                               'pins': [(50, 10), (51, 15)],
                               'type': 'LOCAL'},
                'NET_302': {   'length': 18,
                               'pins': [(93, 32), (86, 21)],
                               'type': 'LOCAL'},
                'NET_303': {   'length': 14,
                               'pins': [(2, 69), (15, 68)],
                               'type': 'LOCAL'},
                'NET_304': {   'length': 12,
                               'pins': [(64, 89), (60, 81)],
                               'type': 'LOCAL'},
                'NET_305': {   'length': 20,
                               'pins': [(72, 56), (88, 52)],
                               'type': 'LOCAL'},
                'NET_306': {   'length': 18,
                               'pins': [(8, 40), (21, 45)],
                               'type': 'LOCAL'},
                'NET_307': {   'length': 6,
                               'pins': [(5, 48), (7, 44)],
                               'type': 'LOCAL'},
                'NET_308': {   'length': 16,
                               'pins': [(32, 91), (41, 98)],
                               'type': 'LOCAL'},
                'NET_309': {   'length': 16,
                               'pins': [(24, 63), (27, 76)],
                               'type': 'LOCAL'},
                'NET_31': {   'length': 6,
                              'pins': [(17, 40), (23, 40)],
                              'type': 'LOCAL'},
                'NET_310': {   'length': 14,
                               'pins': [(38, 35), (33, 26)],
                               'type': 'LOCAL'},
                'NET_311': {   'length': 19,
                               'pins': [(26, 9), (38, 16)],
                               'type': 'LOCAL'},
                'NET_312': {   'length': 15,
                               'pins': [(56, 62), (60, 51)],
                               'type': 'LOCAL'},
                'NET_313': {   'length': 17,
                               'pins': [(3, 69), (19, 70)],
                               'type': 'LOCAL'},
                'NET_314': {   'length': 17,
                               'pins': [(10, 56), (13, 42)],
                               'type': 'LOCAL'},
                'NET_315': {   'length': 7,
                               'pins': [(86, 97), (81, 95)],
                               'type': 'LOCAL'},
                'NET_316': {   'length': 7,
                               'pins': [(96, 42), (96, 49)],
                               'type': 'LOCAL'},
                'NET_317': {   'length': 8,
                               'pins': [(2, 30), (8, 28)],
                               'type': 'LOCAL'},
                'NET_318': {   'length': 20,
                               'pins': [(52, 41), (46, 55)],
                               'type': 'LOCAL'},
                'NET_319': {   'length': 11,
                               'pins': [(25, 61), (14, 61)],
                               'type': 'LOCAL'},
                'NET_32': {   'length': 19,
                              'pins': [(77, 2), (61, 5)],
                              'type': 'LOCAL'},
                'NET_320': {   'length': 15,
                               'pins': [(91, 33), (84, 25)],
                               'type': 'LOCAL'},
                'NET_321': {   'length': 15,
                               'pins': [(8, 22), (1, 30)],
                               'type': 'LOCAL'},
                'NET_322': {   'length': 8,
                               'pins': [(69, 92), (73, 88)],
                               'type': 'LOCAL'},
                'NET_323': {   'length': 9,
                               'pins': [(88, 12), (89, 20)],
                               'type': 'LOCAL'},
                'NET_324': {   'length': 16,
                               'pins': [(1, 33), (13, 37)],
                               'type': 'LOCAL'},
                'NET_325': {   'length': 16,
                               'pins': [(14, 47), (11, 34)],
                               'type': 'LOCAL'},
                'NET_326': {   'length': 5,
                               'pins': [(85, 58), (87, 61)],
                               'type': 'LOCAL'},
                'NET_327': {   'length': 9,
                               'pins': [(21, 11), (21, 2)],
                               'type': 'LOCAL'},
                'NET_328': {   'length': 9,
                               'pins': [(37, 59), (30, 61)],
                               'type': 'LOCAL'},
                'NET_329': {   'length': 6,
                               'pins': [(88, 4), (94, 4)],
                               'type': 'LOCAL'},
                'NET_33': {   'length': 7,
                              'pins': [(48, 0), (52, 3)],
                              'type': 'LOCAL'},
                'NET_330': {   'length': 15,
                               'pins': [(10, 89), (2, 96)],
                               'type': 'LOCAL'},
                'NET_331': {   'length': 20,
                               'pins': [(2, 34), (3, 15)],
                               'type': 'LOCAL'},
                'NET_332': {   'length': 12,
                               'pins': [(84, 50), (84, 62)],
                               'type': 'LOCAL'},
                'NET_333': {   'length': 10,
                               'pins': [(44, 43), (47, 50)],
                               'type': 'LOCAL'},
                'NET_334': {   'length': 19,
                               'pins': [(0, 78), (1, 60)],
                               'type': 'LOCAL'},
                'NET_335': {   'length': 18,
                               'pins': [(12, 33), (26, 37)],
                               'type': 'LOCAL'},
                'NET_336': {   'length': 20,
                               'pins': [(30, 95), (21, 84)],
                               'type': 'LOCAL'},
                'NET_337': {   'length': 5,
                               'pins': [(10, 26), (9, 30)],
                               'type': 'LOCAL'},
                'NET_338': {   'length': 10,
                               'pins': [(58, 70), (51, 67)],
                               'type': 'LOCAL'},
                'NET_339': {   'length': 13,
                               'pins': [(28, 2), (31, 12)],
                               'type': 'LOCAL'},
                'NET_34': {   'length': 18,
                              'pins': [(80, 28), (97, 29)],
                              'type': 'LOCAL'},
                'NET_340': {   'length': 14,
                               'pins': [(4, 23), (11, 16)],
                               'type': 'LOCAL'},
                'NET_341': {   'length': 4,
                               'pins': [(15, 48), (14, 45)],
                               'type': 'LOCAL'},
                'NET_342': {   'length': 7,
                               'pins': [(98, 79), (99, 85)],
                               'type': 'LOCAL'},
                'NET_343': {   'length': 3,
                               'pins': [(14, 30), (12, 31)],
                               'type': 'LOCAL'},
                'NET_344': {   'length': 17,
                               'pins': [(28, 39), (36, 30)],
                               'type': 'LOCAL'},
                'NET_345': {   'length': 16,
                               'pins': [(93, 84), (84, 77)],
                               'type': 'LOCAL'},
                'NET_346': {   'length': 14,
                               'pins': [(33, 60), (21, 58)],
                               'type': 'LOCAL'},
                'NET_347': {   'length': 11,
                               'pins': [(28, 99), (27, 89)],
                               'type': 'LOCAL'},
                'NET_348': {   'length': 16,
                               'pins': [(90, 25), (99, 32)],
                               'type': 'LOCAL'},
                'NET_349': {   'length': 18,
                               'pins': [(16, 94), (10, 82)],
                               'type': 'LOCAL'},
                'NET_35': {   'length': 9,
                              'pins': [(32, 38), (37, 42)],
                              'type': 'LOCAL'},
                'NET_350': {   'length': 3,
                               'pins': [(34, 35), (32, 36)],
                               'type': 'LOCAL'},
                'NET_351': {   'length': 19,
                               'pins': [(31, 77), (49, 78)],
                               'type': 'LOCAL'},
                'NET_352': {   'length': 19,
                               'pins': [(30, 30), (28, 13)],
                               'type': 'LOCAL'},
                'NET_353': {   'length': 18,
                               'pins': [(28, 82), (31, 97)],
                               'type': 'LOCAL'},
                'NET_354': {   'length': 4,
                               'pins': [(97, 36), (96, 39)],
                               'type': 'LOCAL'},
                'NET_355': {   'length': 15,
                               'pins': [(70, 74), (81, 70)],
                               'type': 'LOCAL'},
                'NET_356': {   'length': 5,
                               'pins': [(45, 20), (43, 23)],
                               'type': 'LOCAL'},
                'NET_357': {   'length': 13,
                               'pins': [(66, 85), (63, 75)],
                               'type': 'LOCAL'},
                'NET_358': {   'length': 17,
                               'pins': [(9, 93), (14, 81)],
                               'type': 'LOCAL'},
                'NET_359': {   'length': 20,
                               'pins': [(69, 40), (86, 43)],
                               'type': 'LOCAL'},
                'NET_36': {   'length': 18,
                              'pins': [(85, 43), (69, 41)],
                              'type': 'LOCAL'},
                'NET_360': {   'length': 8,
                               'pins': [(46, 59), (39, 58)],
                               'type': 'LOCAL'},
                'NET_361': {   'length': 12,
                               'pins': [(78, 18), (66, 18)],
                               'type': 'LOCAL'},
                'NET_362': {   'length': 19,
                               'pins': [(76, 47), (62, 42)],
                               'type': 'LOCAL'},
                'NET_363': {   'length': 10,
                               'pins': [(78, 69), (87, 70)],
                               'type': 'LOCAL'},
                'NET_364': {   'length': 14,
                               'pins': [(83, 81), (96, 80)],
                               'type': 'LOCAL'},
                'NET_365': {   'length': 3,
                               'pins': [(74, 29), (72, 28)],
                               'type': 'LOCAL'},
                'NET_366': {   'length': 4,
                               'pins': [(95, 60), (97, 58)],
                               'type': 'LOCAL'},
                'NET_367': {   'length': 16,
                               'pins': [(85, 71), (83, 57)],
                               'type': 'LOCAL'},
                'NET_368': {   'length': 18,
                               'pins': [(87, 66), (70, 67)],
                               'type': 'LOCAL'},
                'NET_369': {   'length': 12,
                               'pins': [(76, 24), (82, 18)],
                               'type': 'LOCAL'},
                'NET_37': {   'length': 3,
                              'pins': [(95, 27), (96, 25)],
                              'type': 'LOCAL'},
                'NET_370': {   'length': 12,
                               'pins': [(62, 58), (71, 55)],
                               'type': 'LOCAL'},
                'NET_371': {   'length': 10,
                               'pins': [(64, 44), (69, 49)],
                               'type': 'LOCAL'},
                'NET_372': {   'length': 11,
                               'pins': [(99, 47), (97, 56)],
                               'type': 'LOCAL'},
                'NET_373': {   'length': 9,
                               'pins': [(86, 72), (91, 76)],
                               'type': 'LOCAL'},
                'NET_374': {   'length': 12,
                               'pins': [(46, 81), (57, 80)],
                               'type': 'LOCAL'},
                'NET_375': {   'length': 11,
                               'pins': [(42, 49), (35, 45)],
                               'type': 'LOCAL'},
                'NET_376': {   'length': 17,
                               'pins': [(78, 19), (82, 6)],
                               'type': 'LOCAL'},
                'NET_377': {   'length': 2,
                               'pins': [(92, 35), (92, 37)],
                               'type': 'LOCAL'},
                'NET_378': {   'length': 18,
                               'pins': [(84, 98), (71, 93)],
                               'type': 'LOCAL'},
                'NET_379': {   'length': 16,
                               'pins': [(5, 64), (7, 50)],
                               'type': 'LOCAL'},
                'NET_38': {   'length': 5,
                              'pins': [(93, 42), (92, 46)],
                              'type': 'LOCAL'},
                'NET_380': {   'length': 19,
                               'pins': [(96, 50), (80, 47)],
                               'type': 'LOCAL'},
                'NET_381': {   'length': 20,
                               'pins': [(85, 68), (73, 76)],
                               'type': 'LOCAL'},
                'NET_382': {   'length': 15,
                               'pins': [(57, 23), (61, 34)],
                               'type': 'LOCAL'},
                'NET_383': {   'length': 6,
                               'pins': [(31, 65), (37, 65)],
                               'type': 'LOCAL'},
                'NET_384': {   'length': 20,
                               'pins': [(35, 72), (22, 79)],
                               'type': 'LOCAL'},
                'NET_385': {   'length': 10,
                               'pins': [(20, 47), (30, 47)],
                               'type': 'LOCAL'},
                'NET_386': {   'length': 17,
                               'pins': [(10, 90), (0, 97)],
                               'type': 'LOCAL'},
                'NET_387': {   'length': 8,
                               'pins': [(82, 74), (86, 70)],
                               'type': 'LOCAL'},
                'NET_388': {   'length': 20,
                               'pins': [(28, 4), (42, 10)],
                               'type': 'LOCAL'},
                'NET_389': {   'length': 10,
                               'pins': [(10, 46), (1, 45)],
                               'type': 'LOCAL'},
                'NET_39': {   'length': 12,
                              'pins': [(64, 81), (73, 84)],
                              'type': 'LOCAL'},
                'NET_390': {   'length': 13,
                               'pins': [(0, 28), (3, 18)],
                               'type': 'LOCAL'},
                'NET_391': {   'length': 4,
                               'pins': [(15, 38), (18, 39)],
                               'type': 'LOCAL'},
                'NET_392': {   'length': 11,
                               'pins': [(9, 2), (0, 4)],
                               'type': 'LOCAL'},
                'NET_393': {   'length': 13,
                               'pins': [(98, 75), (98, 62)],
                               'type': 'LOCAL'},
                'NET_394': {   'length': 19,
                               'pins': [(41, 3), (41, 22)],
                               'type': 'LOCAL'},
                'NET_395': {   'length': 19,
                               'pins': [(49, 89), (35, 84)],
                               'type': 'LOCAL'},
                'NET_396': {   'length': 6,
                               'pins': [(18, 64), (22, 66)],
                               'type': 'LOCAL'},
                'NET_397': {   'length': 13,
                               'pins': [(62, 63), (55, 57)],
                               'type': 'LOCAL'},
                'NET_398': {   'length': 18,
                               'pins': [(80, 79), (74, 91)],
                               'type': 'LOCAL'},
                'NET_399': {   'length': 12,
                               'pins': [(21, 85), (26, 92)],
                               'type': 'LOCAL'},
                'NET_4': {   'length': 11,
                             'pins': [(46, 26), (53, 22)],
                             'type': 'LOCAL'},
                'NET_40': {   'length': 8,
                              'pins': [(41, 88), (39, 82)],
                              'type': 'LOCAL'},
                'NET_400': {   'length': 28,
                               'pins': [(73, 99), (85, 83)],
                               'type': 'MEDIUM'},
                'NET_401': {   'length': 39,
                               'pins': [(49, 72), (37, 99)],
                               'type': 'MEDIUM'},
                'NET_402': {   'length': 49,
                               'pins': [(14, 48), (43, 68)],
                               'type': 'MEDIUM'},
                'NET_403': {   'length': 23,
                               'pins': [(37, 62), (42, 80)],
                               'type': 'MEDIUM'},
                'NET_404': {   'length': 44,
                               'pins': [(58, 80), (71, 49)],
                               'type': 'MEDIUM'},
                'NET_405': {   'length': 25,
                               'pins': [(93, 39), (74, 45)],
                               'type': 'MEDIUM'},
                'NET_406': {   'length': 36,
                               'pins': [(39, 87), (15, 75)],
                               'type': 'MEDIUM'},
                'NET_407': {   'length': 28,
                               'pins': [(78, 14), (55, 9)],
                               'type': 'MEDIUM'},
                'NET_408': {   'length': 31,
                               'pins': [(97, 19), (74, 27)],
                               'type': 'MEDIUM'},
                'NET_409': {   'length': 44,
                               'pins': [(1, 58), (37, 66)],
                               'type': 'MEDIUM'},
                'NET_41': {   'length': 14,
                              'pins': [(19, 63), (33, 63)],
                              'type': 'LOCAL'},
                'NET_410': {   'length': 36,
                               'pins': [(41, 48), (51, 22)],
                               'type': 'MEDIUM'},
                'NET_411': {   'length': 46,
                               'pins': [(72, 21), (84, 55)],
                               'type': 'MEDIUM'},
                'NET_412': {   'length': 35,
                               'pins': [(63, 6), (33, 11)],
                               'type': 'MEDIUM'},
                'NET_413': {   'length': 37,
                               'pins': [(22, 11), (56, 14)],
                               'type': 'MEDIUM'},
                'NET_414': {   'length': 30,
                               'pins': [(8, 49), (27, 38)],
                               'type': 'MEDIUM'},
                'NET_415': {   'length': 31,
                               'pins': [(14, 2), (29, 18)],
                               'type': 'MEDIUM'},
                'NET_416': {   'length': 23,
                               'pins': [(50, 84), (52, 63)],
                               'type': 'MEDIUM'},
                'NET_417': {   'length': 47,
                               'pins': [(69, 86), (79, 49)],
                               'type': 'MEDIUM'},
                'NET_418': {   'length': 38,
                               'pins': [(29, 98), (64, 95)],
                               'type': 'MEDIUM'},
                'NET_419': {   'length': 36,
                               'pins': [(47, 26), (32, 5)],
                               'type': 'MEDIUM'},
                'NET_42': {   'length': 11,
                              'pins': [(88, 67), (84, 74)],
                              'type': 'LOCAL'},
                'NET_420': {   'length': 26,
                               'pins': [(11, 21), (37, 21)],
                               'type': 'MEDIUM'},
                'NET_421': {   'length': 20,
                               'pins': [(63, 27), (76, 34)],
                               'type': 'MEDIUM'},
                'NET_422': {   'length': 36,
                               'pins': [(73, 40), (86, 17)],
                               'type': 'MEDIUM'},
                'NET_423': {   'length': 41,
                               'pins': [(65, 43), (92, 29)],
                               'type': 'MEDIUM'},
                'NET_424': {   'length': 38,
                               'pins': [(36, 90), (14, 74)],
                               'type': 'MEDIUM'},
                'NET_425': {   'length': 48,
                               'pins': [(49, 49), (64, 16)],
                               'type': 'MEDIUM'},
                'NET_426': {   'length': 30,
                               'pins': [(7, 36), (24, 23)],
                               'type': 'MEDIUM'},
                'NET_427': {   'length': 50,
                               'pins': [(51, 90), (8, 83)],
                               'type': 'MEDIUM'},
                'NET_428': {   'length': 47,
                               'pins': [(57, 61), (89, 76)],
                               'type': 'MEDIUM'},
                'NET_429': {   'length': 50,
                               'pins': [(9, 59), (38, 80)],
                               'type': 'MEDIUM'},
                'NET_43': {   'length': 19,
                              'pins': [(89, 49), (97, 38)],
                              'type': 'LOCAL'},
                'NET_430': {   'length': 27,
                               'pins': [(5, 49), (17, 34)],
                               'type': 'MEDIUM'},
                'NET_431': {   'length': 46,
                               'pins': [(55, 4), (37, 32)],
                               'type': 'MEDIUM'},
                'NET_432': {   'length': 48,
                               'pins': [(88, 5), (86, 51)],
                               'type': 'MEDIUM'},
                'NET_433': {   'length': 50,
                               'pins': [(0, 47), (36, 33)],
                               'type': 'MEDIUM'},
                'NET_434': {   'length': 34,
                               'pins': [(58, 62), (52, 90)],
                               'type': 'MEDIUM'},
                'NET_435': {   'length': 22,
                               'pins': [(29, 83), (13, 77)],
                               'type': 'MEDIUM'},
                'NET_436': {   'length': 29,
                               'pins': [(91, 34), (67, 39)],
                               'type': 'MEDIUM'},
                'NET_437': {   'length': 34,
                               'pins': [(66, 52), (81, 71)],
                               'type': 'MEDIUM'},
                'NET_438': {   'length': 27,
                               'pins': [(98, 43), (72, 42)],
                               'type': 'MEDIUM'},
                'NET_439': {   'length': 31,
                               'pins': [(7, 99), (28, 89)],
                               'type': 'MEDIUM'},
                'NET_44': {   'length': 20,
                              'pins': [(35, 66), (18, 69)],
                              'type': 'LOCAL'},
                'NET_440': {   'length': 21,
                               'pins': [(18, 36), (1, 40)],
                               'type': 'MEDIUM'},
                'NET_441': {   'length': 46,
                               'pins': [(35, 4), (43, 42)],
                               'type': 'MEDIUM'},
                'NET_442': {   'length': 45,
                               'pins': [(43, 82), (71, 65)],
                               'type': 'MEDIUM'},
                'NET_443': {   'length': 43,
                               'pins': [(59, 98), (38, 76)],
                               'type': 'MEDIUM'},
                'NET_444': {   'length': 31,
                               'pins': [(41, 87), (12, 85)],
                               'type': 'MEDIUM'},
                'NET_445': {   'length': 32,
                               'pins': [(21, 24), (3, 10)],
                               'type': 'MEDIUM'},
                'NET_446': {   'length': 26,
                               'pins': [(74, 66), (87, 79)],
                               'type': 'MEDIUM'},
                'NET_447': {   'length': 31,
                               'pins': [(34, 97), (20, 80)],
                               'type': 'MEDIUM'},
                'NET_448': {   'length': 43,
                               'pins': [(65, 15), (69, 54)],
                               'type': 'MEDIUM'},
                'NET_449': {   'length': 43,
                               'pins': [(6, 36), (45, 40)],
                               'type': 'MEDIUM'},
                'NET_45': {   'length': 19,
                              'pins': [(55, 63), (50, 49)],
                              'type': 'LOCAL'},
                'NET_450': {   'length': 46,
                               'pins': [(53, 53), (67, 21)],
                               'type': 'MEDIUM'},
                'NET_451': {   'length': 43,
                               'pins': [(13, 66), (37, 47)],
                               'type': 'MEDIUM'},
                'NET_452': {   'length': 24,
                               'pins': [(29, 24), (17, 12)],
                               'type': 'MEDIUM'},
                'NET_453': {   'length': 26,
                               'pins': [(23, 34), (38, 45)],
                               'type': 'MEDIUM'},
                'NET_454': {   'length': 20,
                               'pins': [(68, 79), (72, 95)],
                               'type': 'MEDIUM'},
                'NET_455': {   'length': 43,
                               'pins': [(62, 84), (72, 51)],
                               'type': 'MEDIUM'},
                'NET_456': {   'length': 43,
                               'pins': [(87, 93), (53, 84)],
                               'type': 'MEDIUM'},
                'NET_457': {   'length': 30,
                               'pins': [(31, 38), (22, 59)],
                               'type': 'MEDIUM'},
                'NET_458': {   'length': 46,
                               'pins': [(75, 90), (35, 96)],
                               'type': 'MEDIUM'},
                'NET_459': {   'length': 26,
                               'pins': [(14, 67), (34, 61)],
                               'type': 'MEDIUM'},
                'NET_46': {   'length': 14,
                              'pins': [(28, 24), (21, 17)],
                              'type': 'LOCAL'},
                'NET_460': {   'length': 45,
                               'pins': [(14, 50), (31, 78)],
                               'type': 'MEDIUM'},
                'NET_461': {   'length': 32,
                               'pins': [(43, 93), (23, 81)],
                               'type': 'MEDIUM'},
                'NET_462': {   'length': 31,
                               'pins': [(83, 32), (58, 38)],
                               'type': 'MEDIUM'},
                'NET_463': {   'length': 45,
                               'pins': [(36, 21), (53, 49)],
                               'type': 'MEDIUM'},
                'NET_464': {   'length': 30,
                               'pins': [(61, 1), (77, 15)],
                               'type': 'MEDIUM'},
                'NET_465': {   'length': 28,
                               'pins': [(87, 83), (74, 68)],
                               'type': 'MEDIUM'},
                'NET_466': {   'length': 39,
                               'pins': [(1, 70), (19, 91)],
                               'type': 'MEDIUM'},
                'NET_467': {   'length': 27,
                               'pins': [(27, 73), (41, 86)],
                               'type': 'MEDIUM'},
                'NET_468': {   'length': 31,
                               'pins': [(8, 68), (21, 86)],
                               'type': 'MEDIUM'},
                'NET_469': {   'length': 33,
                               'pins': [(49, 25), (17, 24)],
                               'type': 'MEDIUM'},
                'NET_47': {   'length': 13,
                              'pins': [(74, 17), (79, 9)],
                              'type': 'LOCAL'},
                'NET_470': {   'length': 38,
                               'pins': [(69, 59), (88, 78)],
                               'type': 'MEDIUM'},
                'NET_471': {   'length': 35,
                               'pins': [(79, 63), (92, 85)],
                               'type': 'MEDIUM'},
                'NET_472': {   'length': 37,
                               'pins': [(95, 63), (68, 53)],
                               'type': 'MEDIUM'},
                'NET_473': {   'length': 41,
                               'pins': [(74, 90), (98, 73)],
                               'type': 'MEDIUM'},
                'NET_474': {   'length': 23,
                               'pins': [(8, 3), (25, 9)],
                               'type': 'MEDIUM'},
                'NET_475': {   'length': 82,
                               'pins': [(31, 27), (92, 48)],
                               'type': 'LONG'},
                'NET_476': {   'length': 105,
                               'pins': [(19, 65), (68, 9)],
                               'type': 'LONG'},
                'NET_477': {   'length': 128,
                               'pins': [(85, 24), (11, 78)],
                               'type': 'LONG'},
                'NET_478': {   'length': 65,
                               'pins': [(23, 31), (23, 96)],
                               'type': 'LONG'},
                'NET_479': {   'length': 74,
                               'pins': [(31, 21), (23, 87)],
                               'type': 'LONG'},
                'NET_48': {   'length': 8,
                              'pins': [(14, 96), (21, 97)],
                              'type': 'LOCAL'},
                'NET_480': {   'length': 61,
                               'pins': [(9, 99), (63, 92)],
                               'type': 'LONG'},
                'NET_481': {   'length': 61,
                               'pins': [(95, 35), (38, 39)],
                               'type': 'LONG'},
                'NET_482': {   'length': 83,
                               'pins': [(24, 64), (76, 95)],
                               'type': 'LONG'},
                'NET_483': {   'length': 64,
                               'pins': [(10, 42), (39, 7)],
                               'type': 'LONG'},
                'NET_484': {   'length': 64,
                               'pins': [(0, 31), (49, 16)],
                               'type': 'LONG'},
                'NET_485': {   'length': 106,
                               'pins': [(64, 99), (15, 42)],
                               'type': 'LONG'},
                'NET_486': {   'length': 168,
                               'pins': [(8, 16), (95, 97)],
                               'type': 'LONG'},
                'NET_487': {   'length': 95,
                               'pins': [(92, 99), (90, 6)],
                               'type': 'LONG'},
                'NET_488': {   'length': 93,
                               'pins': [(49, 90), (38, 8)],
                               'type': 'LONG'},
                'NET_489': {   'length': 88,
                               'pins': [(19, 33), (79, 5)],
                               'type': 'LONG'},
                'NET_49': {   'length': 16,
                              'pins': [(24, 76), (35, 81)],
                              'type': 'LOCAL'},
                'NET_490': {   'length': 132,
                               'pins': [(91, 1), (50, 92)],
                               'type': 'LONG'},
                'NET_491': {   'length': 59,
                               'pins': [(56, 44), (72, 1)],
                               'type': 'LONG'},
                'NET_492': {   'length': 62,
                               'pins': [(68, 39), (10, 35)],
                               'type': 'LONG'},
                'NET_493': {   'length': 87,
                               'pins': [(87, 97), (84, 13)],
                               'type': 'LONG'},
                'NET_494': {   'length': 75,
                               'pins': [(69, 53), (0, 59)],
                               'type': 'LONG'},
                'NET_495': {   'length': 68,
                               'pins': [(28, 25), (76, 5)],
                               'type': 'LONG'},
                'NET_496': {   'length': 51,
                               'pins': [(0, 18), (6, 63)],
                               'type': 'LONG'},
                'NET_497': {   'length': 55,
                               'pins': [(51, 47), (78, 75)],
                               'type': 'LONG'},
                'NET_498': {   'length': 127,
                               'pins': [(79, 66), (17, 1)],
                               'type': 'LONG'},
                'NET_499': {   'length': 89,
                               'pins': [(73, 4), (33, 53)],
                               'type': 'LONG'},
                'NET_5': {   'length': 18,
                             'pins': [(74, 26), (80, 38)],
                             'type': 'LOCAL'},
                'NET_50': {   'length': 12,
                              'pins': [(90, 59), (88, 69)],
                              'type': 'LOCAL'},
                'NET_51': {   'length': 20,
                              'pins': [(39, 95), (22, 98)],
                              'type': 'LOCAL'},
                'NET_52': {   'length': 18,
                              'pins': [(6, 83), (20, 87)],
                              'type': 'LOCAL'},
                'NET_53': {   'length': 18,
                              'pins': [(32, 6), (17, 3)],
                              'type': 'LOCAL'},
                'NET_54': {   'length': 19,
                              'pins': [(3, 52), (15, 59)],
                              'type': 'LOCAL'},
                'NET_55': {   'length': 14,
                              'pins': [(84, 34), (71, 33)],
                              'type': 'LOCAL'},
                'NET_56': {   'length': 20,
                              'pins': [(94, 79), (86, 91)],
                              'type': 'LOCAL'},
                'NET_57': {   'length': 6,
                              'pins': [(53, 42), (57, 44)],
                              'type': 'LOCAL'},
                'NET_58': {   'length': 11,
                              'pins': [(63, 96), (73, 97)],
                              'type': 'LOCAL'},
                'NET_59': {   'length': 17,
                              'pins': [(17, 15), (4, 11)],
                              'type': 'LOCAL'},
                'NET_6': {   'length': 13,
                             'pins': [(54, 40), (52, 51)],
                             'type': 'LOCAL'},
                'NET_60': {   'length': 13,
                              'pins': [(5, 82), (18, 82)],
                              'type': 'LOCAL'},
                'NET_61': {   'length': 5,
                              'pins': [(23, 98), (27, 99)],
                              'type': 'LOCAL'},
                'NET_62': {   'length': 18,
                              'pins': [(78, 86), (91, 81)],
                              'type': 'LOCAL'},
                'NET_63': {   'length': 15,
                              'pins': [(83, 52), (91, 45)],
                              'type': 'LOCAL'},
                'NET_64': {   'length': 15,
                              'pins': [(60, 53), (58, 40)],
                              'type': 'LOCAL'},
                'NET_65': {   'length': 16,
                              'pins': [(47, 99), (53, 89)],
                              'type': 'LOCAL'},
                'NET_66': {   'length': 12,
                              'pins': [(99, 22), (88, 21)],
                              'type': 'LOCAL'},
                'NET_67': {   'length': 16,
                              'pins': [(61, 31), (47, 29)],
                              'type': 'LOCAL'},
                'NET_68': {   'length': 10,
                              'pins': [(95, 68), (88, 71)],
                              'type': 'LOCAL'},
                'NET_69': {   'length': 17,
                              'pins': [(39, 6), (26, 2)],
                              'type': 'LOCAL'},
                'NET_7': {   'length': 18,
                             'pins': [(72, 35), (75, 50)],
                             'type': 'LOCAL'},
                'NET_70': {   'length': 9,
                              'pins': [(16, 3), (19, 9)],
                              'type': 'LOCAL'},
                'NET_71': {   'length': 6,
                              'pins': [(11, 17), (16, 18)],
                              'type': 'LOCAL'},
                'NET_72': {   'length': 13,
                              'pins': [(26, 33), (38, 32)],
                              'type': 'LOCAL'},
                'NET_73': {   'length': 20,
                              'pins': [(26, 81), (10, 85)],
                              'type': 'LOCAL'},
                'NET_74': {   'length': 17,
                              'pins': [(7, 57), (5, 42)],
                              'type': 'LOCAL'},
                'NET_75': {   'length': 14,
                              'pins': [(76, 9), (77, 22)],
                              'type': 'LOCAL'},
                'NET_76': {   'length': 20,
                              'pins': [(25, 40), (31, 54)],
                              'type': 'LOCAL'},
                'NET_77': {   'length': 5,
                              'pins': [(23, 38), (21, 35)],
                              'type': 'LOCAL'},
                'NET_78': {   'length': 14,
                              'pins': [(69, 89), (56, 90)],
                              'type': 'LOCAL'},
                'NET_79': {   'length': 14,
                              'pins': [(1, 57), (14, 58)],
                              'type': 'LOCAL'},
                'NET_8': {   'length': 19,
                             'pins': [(6, 44), (21, 48)],
                             'type': 'LOCAL'},
                'NET_80': {   'length': 15,
                              'pins': [(84, 79), (95, 83)],
                              'type': 'LOCAL'},
                'NET_81': {   'length': 15,
                              'pins': [(81, 87), (94, 89)],
                              'type': 'LOCAL'},
                'NET_82': {   'length': 15,
                              'pins': [(19, 45), (13, 54)],
                              'type': 'LOCAL'},
                'NET_83': {   'length': 20,
                              'pins': [(73, 79), (83, 69)],
                              'type': 'LOCAL'},
                'NET_84': {   'length': 20,
                              'pins': [(71, 8), (58, 15)],
                              'type': 'LOCAL'},
                'NET_85': {   'length': 4,
                              'pins': [(77, 40), (74, 41)],
                              'type': 'LOCAL'},
                'NET_86': {   'length': 18,
                              'pins': [(68, 77), (85, 78)],
                              'type': 'LOCAL'},
                'NET_87': {   'length': 19,
                              'pins': [(91, 85), (82, 75)],
                              'type': 'LOCAL'},
                'NET_88': {   'length': 3,
                              'pins': [(46, 89), (48, 90)],
                              'type': 'LOCAL'},
                'NET_89': {   'length': 9,
                              'pins': [(98, 69), (95, 75)],
                              'type': 'LOCAL'},
                'NET_9': {   'length': 15,
                             'pins': [(39, 0), (34, 10)],
                             'type': 'LOCAL'},
                'NET_90': {   'length': 19,
                              'pins': [(52, 59), (34, 58)],
                              'type': 'LOCAL'},
                'NET_91': {   'length': 15,
                              'pins': [(50, 37), (54, 26)],
                              'type': 'LOCAL'},
                'NET_92': {   'length': 15,
                              'pins': [(68, 26), (67, 40)],
                              'type': 'LOCAL'},
                'NET_93': {   'length': 11,
                              'pins': [(1, 3), (12, 3)],
                              'type': 'LOCAL'},
                'NET_94': {   'length': 18,
                              'pins': [(93, 24), (88, 37)],
                              'type': 'LOCAL'},
                'NET_95': {   'length': 17,
                              'pins': [(82, 4), (82, 21)],
                              'type': 'LOCAL'},
                'NET_96': {   'length': 17,
                              'pins': [(66, 2), (56, 9)],
                              'type': 'LOCAL'},
                'NET_97': {   'length': 17,
                              'pins': [(34, 16), (20, 19)],
                              'type': 'LOCAL'},
                'NET_98': {   'length': 16,
                              'pins': [(53, 14), (64, 19)],
                              'type': 'LOCAL'},
                'NET_99': {   'length': 13,
                              'pins': [(90, 35), (83, 29)],
                              'type': 'LOCAL'}}}
