# Greedy reference routed solution

data = {   'meta': {   'grid_size': 100,
                'layer_directions': {   'M2': 'V',
                                        'M3': 'H',
                                        'M4': 'V',
                                        'M5': 'H',
                                        'M6': 'V',
                                        'M7': 'H',
                                        'M8': 'V',
                                        'M9': 'H'},
                'total_cost': 123},
    'nets': {   'NET_0': {   'cost': 7,
                             'pins': [(99, 56), (99, 59)],
                             'segments': [   {   'end': (99, 56, 'M2'),
                                                 'start': (99, 56, 'M1')},
                                             {   'end': (99, 59, 'M2'),
                                                 'start': (99, 56, 'M2')},
                                             {   'end': (99, 59, 'M1'),
                                                 'start': (99, 59, 'M2')}]},
                'NET_1': {   'cost': 56,
                             'pins': [(5, 72), (44, 63)],
                             'segments': [   {   'end': (5, 72, 'M2'),
                                                 'start': (5, 72, 'M1')},
                                             {   'end': (5, 63, 'M2'),
                                                 'start': (5, 72, 'M2')},
                                             {   'end': (5, 63, 'M3'),
                                                 'start': (5, 63, 'M2')},
                                             {   'end': (44, 63, 'M3'),
                                                 'start': (5, 63, 'M3')},
                                             {   'end': (44, 63, 'M2'),
                                                 'start': (44, 63, 'M3')},
                                             {   'end': (44, 63, 'M1'),
                                                 'start': (44, 63, 'M2')}]},
                'NET_2': {   'cost': 60,
                             'pins': [(43, 74), (5, 60)],
                             'segments': [   {   'end': (43, 74, 'M2'),
                                                 'start': (43, 74, 'M1')},
                                             {   'end': (43, 60, 'M2'),
                                                 'start': (43, 74, 'M2')},
                                             {   'end': (43, 60, 'M3'),
                                                 'start': (43, 60, 'M2')},
                                             {   'end': (5, 60, 'M3'),
                                                 'start': (43, 60, 'M3')},
                                             {   'end': (5, 60, 'M2'),
                                                 'start': (5, 60, 'M3')},
                                             {   'end': (5, 60, 'M1'),
                                                 'start': (5, 60, 'M2')}]}}}
