# Auto-generated router-visible netlist
# No optimal metadata included

data = {   'grid_size': 100,
    'nets': {   'NET_0': {   'length': 3,
                             'pins': [(99, 56), (99, 59)],
                             'type': 'LOCAL'},
                'NET_1': {   'length': 12,
                             'pins': [(5, 72), (5, 60)],
                             'type': 'LOCAL'},
                'NET_10': {   'length': 17,
                              'pins': [(97, 67), (87, 74)],
                              'type': 'LOCAL'},
                'NET_100': {   'length': 17,
                               'pins': [(67, 87), (75, 96)],
                               'type': 'LOCAL'},
                'NET_101': {   'length': 11,
                               'pins': [(18, 46), (21, 38)],
                               'type': 'LOCAL'},
                'NET_102': {   'length': 7,
                               'pins': [(56, 99), (60, 96)],
                               'type': 'LOCAL'},
                'NET_103': {   'length': 19,
                               'pins': [(16, 11), (6, 20)],
                               'type': 'LOCAL'},
                'NET_104': {   'length': 12,
                               'pins': [(12, 53), (19, 48)],
                               'type': 'LOCAL'},
                'NET_105': {   'length': 8,
                               'pins': [(43, 31), (40, 36)],
                               'type': 'LOCAL'},
                'NET_106': {   'length': 19,
                               'pins': [(60, 65), (48, 72)],
                               'type': 'LOCAL'},
                'NET_107': {   'length': 15,
                               'pins': [(97, 50), (96, 64)],
                               'type': 'LOCAL'},
                'NET_108': {   'length': 13,
                               'pins': [(71, 79), (63, 84)],
                               'type': 'LOCAL'},
                'NET_109': {   'length': 19,
                               'pins': [(11, 9), (21, 18)],
                               'type': 'LOCAL'},
                'NET_11': {   'length': 8,
                              'pins': [(42, 72), (44, 66)],
                              'type': 'LOCAL'},
                'NET_110': {   'length': 14,
                               'pins': [(81, 88), (78, 99)],
                               'type': 'LOCAL'},
                'NET_111': {   'length': 11,
                               'pins': [(23, 54), (21, 63)],
                               'type': 'LOCAL'},
                'NET_112': {   'length': 14,
                               'pins': [(9, 85), (0, 90)],
                               'type': 'LOCAL'},
                'NET_113': {   'length': 13,
                               'pins': [(27, 11), (38, 9)],
                               'type': 'LOCAL'},
                'NET_114': {   'length': 6,
                               'pins': [(78, 70), (78, 76)],
                               'type': 'LOCAL'},
                'NET_115': {   'length': 3,
                               'pins': [(42, 31), (40, 30)],
                               'type': 'LOCAL'},
                'NET_116': {   'length': 15,
                               'pins': [(75, 70), (72, 82)],
                               'type': 'LOCAL'},
                'NET_117': {   'length': 5,
                               'pins': [(95, 87), (93, 90)],
                               'type': 'LOCAL'},
                'NET_118': {   'length': 15,
                               'pins': [(47, 53), (40, 45)],
                               'type': 'LOCAL'},
                'NET_119': {   'length': 10,
                               'pins': [(86, 99), (91, 94)],
                               'type': 'LOCAL'},
                'NET_12': {   'length': 4,
                              'pins': [(88, 98), (86, 96)],
                              'type': 'LOCAL'},
                'NET_120': {   'length': 13,
                               'pins': [(16, 99), (23, 93)],
                               'type': 'LOCAL'},
                'NET_121': {   'length': 20,
                               'pins': [(7, 55), (2, 40)],
                               'type': 'LOCAL'},
                'NET_122': {   'length': 11,
                               'pins': [(8, 17), (3, 11)],
                               'type': 'LOCAL'},
                'NET_123': {   'length': 17,
                               'pins': [(13, 39), (25, 34)],
                               'type': 'LOCAL'},
                'NET_124': {   'length': 16,
                               'pins': [(7, 37), (11, 25)],
                               'type': 'LOCAL'},
                'NET_125': {   'length': 11,
                               'pins': [(9, 42), (18, 44)],
                               'type': 'LOCAL'},
                'NET_126': {   'length': 16,
                               'pins': [(4, 21), (6, 35)],
                               'type': 'LOCAL'},
                'NET_127': {   'length': 15,
                               'pins': [(79, 77), (64, 77)],
                               'type': 'LOCAL'},
                'NET_128': {   'length': 6,
                               'pins': [(58, 75), (59, 70)],
                               'type': 'LOCAL'},
                'NET_129': {   'length': 16,
                               'pins': [(31, 47), (23, 55)],
                               'type': 'LOCAL'},
                'NET_13': {   'length': 9,
                              'pins': [(83, 30), (82, 22)],
                              'type': 'LOCAL'},
                'NET_130': {   'length': 18,
                               'pins': [(37, 44), (23, 48)],
                               'type': 'LOCAL'},
                'NET_131': {   'length': 11,
                               'pins': [(18, 17), (12, 12)],
                               'type': 'LOCAL'},
                'NET_132': {   'length': 10,
                               'pins': [(79, 15), (84, 20)],
                               'type': 'LOCAL'},
                'NET_133': {   'length': 19,
                               'pins': [(57, 72), (74, 74)],
                               'type': 'LOCAL'},
                'NET_134': {   'length': 15,
                               'pins': [(11, 64), (0, 68)],
                               'type': 'LOCAL'},
                'NET_135': {   'length': 12,
                               'pins': [(28, 18), (17, 19)],
                               'type': 'LOCAL'},
                'NET_136': {   'length': 6,
                               'pins': [(90, 44), (90, 38)],
                               'type': 'LOCAL'},
                'NET_137': {   'length': 20,
                               'pins': [(38, 52), (48, 62)],
                               'type': 'LOCAL'},
                'NET_138': {   'length': 20,
                               'pins': [(6, 55), (20, 61)],
                               'type': 'LOCAL'},
                'NET_139': {   'length': 8,
                               'pins': [(9, 16), (13, 12)],
                               'type': 'LOCAL'},
                'NET_14': {   'length': 15,
                              'pins': [(58, 21), (56, 34)],
                              'type': 'LOCAL'},
                'NET_140': {   'length': 15,
                               'pins': [(81, 90), (91, 95)],
                               'type': 'LOCAL'},
                'NET_141': {   'length': 5,
                               'pins': [(14, 79), (12, 82)],
                               'type': 'LOCAL'},
                'NET_142': {   'length': 16,
                               'pins': [(31, 58), (29, 44)],
                               'type': 'LOCAL'},
                'NET_143': {   'length': 14,
                               'pins': [(47, 64), (54, 57)],
                               'type': 'LOCAL'},
                'NET_144': {   'length': 20,
                               'pins': [(52, 74), (42, 64)],
                               'type': 'LOCAL'},
                'NET_145': {   'length': 19,
                               'pins': [(53, 16), (58, 2)],
                               'type': 'LOCAL'},
                'NET_146': {   'length': 10,
                               'pins': [(71, 20), (75, 14)],
                               'type': 'LOCAL'},
                'NET_147': {   'length': 18,
                               'pins': [(58, 52), (41, 53)],
                               'type': 'LOCAL'},
                'NET_148': {   'length': 20,
                               'pins': [(37, 39), (43, 25)],
                               'type': 'LOCAL'},
                'NET_149': {   'length': 18,
                               'pins': [(59, 0), (54, 13)],
                               'type': 'LOCAL'},
                'NET_15': {   'length': 15,
                              'pins': [(93, 22), (98, 32)],
                              'type': 'LOCAL'},
                'NET_150': {   'length': 14,
                               'pins': [(32, 8), (25, 1)],
                               'type': 'LOCAL'},
                'NET_151': {   'length': 8,
                               'pins': [(26, 48), (18, 48)],
                               'type': 'LOCAL'},
                'NET_152': {   'length': 3,
                               'pins': [(49, 93), (52, 93)],
                               'type': 'LOCAL'},
                'NET_153': {   'length': 20,
                               'pins': [(1, 36), (1, 56)],
                               'type': 'LOCAL'},
                'NET_154': {   'length': 16,
                               'pins': [(73, 32), (80, 41)],
                               'type': 'LOCAL'},
                'NET_155': {   'length': 3,
                               'pins': [(5, 81), (7, 82)],
                               'type': 'LOCAL'},
                'NET_156': {   'length': 14,
                               'pins': [(81, 93), (70, 90)],
                               'type': 'LOCAL'},
                'NET_157': {   'length': 14,
                               'pins': [(97, 85), (84, 84)],
                               'type': 'LOCAL'},
                'NET_158': {   'length': 13,
                               'pins': [(37, 68), (46, 64)],
                               'type': 'LOCAL'},
                'NET_159': {   'length': 8,
                               'pins': [(62, 18), (68, 20)],
                               'type': 'LOCAL'},
                'NET_16': {   'length': 20,
                              'pins': [(30, 89), (22, 77)],
                              'type': 'LOCAL'},
                'NET_160': {   'length': 6,
                               'pins': [(76, 62), (82, 62)],
                               'type': 'LOCAL'},
                'NET_161': {   'length': 17,
                               'pins': [(3, 65), (2, 49)],
                               'type': 'LOCAL'},
                'NET_162': {   'length': 12,
                               'pins': [(88, 11), (95, 16)],
                               'type': 'LOCAL'},
                'NET_163': {   'length': 20,
                               'pins': [(32, 71), (25, 58)],
                               'type': 'LOCAL'},
                'NET_164': {   'length': 9,
                               'pins': [(12, 63), (15, 57)],
                               'type': 'LOCAL'},
                'NET_165': {   'length': 10,
                               'pins': [(17, 42), (7, 42)],
                               'type': 'LOCAL'},
                'NET_166': {   'length': 9,
                               'pins': [(62, 59), (59, 53)],
                               'type': 'LOCAL'},
                'NET_167': {   'length': 11,
                               'pins': [(98, 92), (90, 89)],
                               'type': 'LOCAL'},
                'NET_168': {   'length': 6,
                               'pins': [(23, 85), (25, 89)],
                               'type': 'LOCAL'},
                'NET_169': {   'length': 6,
                               'pins': [(39, 92), (35, 94)],
                               'type': 'LOCAL'},
                'NET_17': {   'length': 18,
                              'pins': [(42, 22), (48, 34)],
                              'type': 'LOCAL'},
                'NET_170': {   'length': 17,
                               'pins': [(35, 80), (44, 88)],
                               'type': 'LOCAL'},
                'NET_171': {   'length': 15,
                               'pins': [(23, 90), (33, 85)],
                               'type': 'LOCAL'},
                'NET_172': {   'length': 12,
                               'pins': [(92, 1), (88, 9)],
                               'type': 'LOCAL'},
                'NET_173': {   'length': 11,
                               'pins': [(87, 1), (96, 3)],
                               'type': 'LOCAL'},
                'NET_174': {   'length': 12,
                               'pins': [(16, 59), (17, 48)],
                               'type': 'LOCAL'},
                'NET_175': {   'length': 9,
                               'pins': [(87, 25), (86, 33)],
                               'type': 'LOCAL'},
                'NET_176': {   'length': 8,
                               'pins': [(53, 62), (49, 58)],
                               'type': 'LOCAL'},
                'NET_177': {   'length': 20,
                               'pins': [(25, 35), (32, 48)],
                               'type': 'LOCAL'},
                'NET_178': {   'length': 15,
                               'pins': [(18, 66), (28, 71)],
                               'type': 'LOCAL'},
                'NET_179': {   'length': 6,
                               'pins': [(42, 86), (40, 90)],
                               'type': 'LOCAL'},
                'NET_18': {   'length': 17,
                              'pins': [(88, 25), (90, 40)],
                              'type': 'LOCAL'},
                'NET_180': {   'length': 12,
                               'pins': [(64, 62), (60, 70)],
                               'type': 'LOCAL'},
                'NET_181': {   'length': 18,
                               'pins': [(91, 60), (93, 44)],
                               'type': 'LOCAL'},
                'NET_182': {   'length': 5,
                               'pins': [(72, 50), (70, 47)],
                               'type': 'LOCAL'},
                'NET_183': {   'length': 16,
                               'pins': [(45, 74), (35, 68)],
                               'type': 'LOCAL'},
                'NET_184': {   'length': 5,
                               'pins': [(2, 28), (4, 31)],
                               'type': 'LOCAL'},
                'NET_185': {   'length': 20,
                               'pins': [(23, 0), (35, 8)],
                               'type': 'LOCAL'},
                'NET_186': {   'length': 18,
                               'pins': [(68, 35), (81, 40)],
                               'type': 'LOCAL'},
                'NET_187': {   'length': 14,
                               'pins': [(26, 65), (31, 56)],
                               'type': 'LOCAL'},
                'NET_188': {   'length': 14,
                               'pins': [(26, 5), (13, 6)],
                               'type': 'LOCAL'},
                'NET_189': {   'length': 16,
                               'pins': [(22, 50), (16, 60)],
                               'type': 'LOCAL'},
                'NET_19': {   'length': 14,
                              'pins': [(78, 31), (69, 26)],
                              'type': 'LOCAL'},
                'NET_190': {   'length': 20,
                               'pins': [(64, 59), (84, 59)],
                               'type': 'LOCAL'},
                'NET_191': {   'length': 16,
                               'pins': [(92, 19), (84, 11)],
                               'type': 'LOCAL'},
                'NET_192': {   'length': 13,
                               'pins': [(24, 59), (34, 62)],
                               'type': 'LOCAL'},
                'NET_193': {   'length': 12,
                               'pins': [(36, 35), (34, 25)],
                               'type': 'LOCAL'},
                'NET_194': {   'length': 7,
                               'pins': [(3, 23), (1, 18)],
                               'type': 'LOCAL'},
                'NET_195': {   'length': 18,
                               'pins': [(67, 23), (53, 27)],
                               'type': 'LOCAL'},
                'NET_196': {   'length': 9,
                               'pins': [(40, 13), (43, 7)],
                               'type': 'LOCAL'},
                'NET_197': {   'length': 9,
                               'pins': [(79, 34), (82, 28)],
                               'type': 'LOCAL'},
                'NET_198': {   'length': 20,
                               'pins': [(52, 79), (57, 94)],
                               'type': 'LOCAL'},
                'NET_199': {   'length': 20,
                               'pins': [(75, 51), (94, 52)],
                               'type': 'LOCAL'},
                'NET_2': {   'length': 17,
                             'pins': [(76, 21), (67, 13)],
                             'type': 'LOCAL'},
                'NET_20': {   'length': 12,
                              'pins': [(55, 56), (66, 57)],
                              'type': 'LOCAL'},
                'NET_200': {   'length': 29,
                               'pins': [(79, 30), (76, 4)],
                               'type': 'MEDIUM'},
                'NET_201': {   'length': 29,
                               'pins': [(17, 95), (24, 73)],
                               'type': 'MEDIUM'},
                'NET_202': {   'length': 21,
                               'pins': [(6, 0), (4, 19)],
                               'type': 'MEDIUM'},
                'NET_203': {   'length': 44,
                               'pins': [(77, 90), (58, 65)],
                               'type': 'MEDIUM'},
                'NET_204': {   'length': 48,
                               'pins': [(93, 49), (80, 14)],
                               'type': 'MEDIUM'},
                'NET_205': {   'length': 48,
                               'pins': [(83, 1), (95, 37)],
                               'type': 'MEDIUM'},
                'NET_206': {   'length': 29,
                               'pins': [(62, 32), (38, 27)],
                               'type': 'MEDIUM'},
                'NET_207': {   'length': 27,
                               'pins': [(1, 1), (18, 11)],
                               'type': 'MEDIUM'},
                'NET_208': {   'length': 27,
                               'pins': [(66, 80), (42, 83)],
                               'type': 'MEDIUM'},
                'NET_209': {   'length': 23,
                               'pins': [(45, 63), (47, 42)],
                               'type': 'MEDIUM'},
                'NET_21': {   'length': 10,
                              'pins': [(84, 87), (86, 79)],
                              'type': 'LOCAL'},
                'NET_210': {   'length': 29,
                               'pins': [(61, 45), (81, 36)],
                               'type': 'MEDIUM'},
                'NET_211': {   'length': 39,
                               'pins': [(77, 32), (53, 47)],
                               'type': 'MEDIUM'},
                'NET_212': {   'length': 22,
                               'pins': [(93, 33), (83, 45)],
                               'type': 'MEDIUM'},
                'NET_213': {   'length': 45,
                               'pins': [(90, 70), (46, 69)],
                               'type': 'MEDIUM'},
                'NET_214': {   'length': 38,
                               'pins': [(83, 67), (78, 34)],
                               'type': 'MEDIUM'},
                'NET_215': {   'length': 48,
                               'pins': [(10, 90), (56, 88)],
                               'type': 'MEDIUM'},
                'NET_216': {   'length': 34,
                               'pins': [(81, 1), (97, 19)],
                               'type': 'MEDIUM'},
                'NET_217': {   'length': 32,
                               'pins': [(39, 60), (66, 55)],
                               'type': 'MEDIUM'},
                'NET_218': {   'length': 44,
                               'pins': [(50, 19), (30, 43)],
                               'type': 'MEDIUM'},
                'NET_219': {   'length': 27,
                               'pins': [(30, 6), (12, 15)],
                               'type': 'MEDIUM'},
                'NET_22': {   'length': 18,
                              'pins': [(52, 86), (34, 86)],
                              'type': 'LOCAL'},
                'NET_220': {   'length': 50,
                               'pins': [(50, 67), (30, 97)],
                               'type': 'MEDIUM'},
                'NET_221': {   'length': 36,
                               'pins': [(11, 45), (3, 73)],
                               'type': 'MEDIUM'},
                'NET_222': {   'length': 29,
                               'pins': [(94, 35), (73, 43)],
                               'type': 'MEDIUM'},
                'NET_223': {   'length': 28,
                               'pins': [(28, 49), (9, 58)],
                               'type': 'MEDIUM'},
                'NET_224': {   'length': 30,
                               'pins': [(69, 17), (94, 22)],
                               'type': 'MEDIUM'},
                'NET_225': {   'length': 32,
                               'pins': [(59, 56), (31, 52)],
                               'type': 'MEDIUM'},
                'NET_226': {   'length': 39,
                               'pins': [(35, 76), (61, 63)],
                               'type': 'MEDIUM'},
                'NET_227': {   'length': 49,
                               'pins': [(58, 55), (12, 58)],
                               'type': 'MEDIUM'},
                'NET_228': {   'length': 39,
                               'pins': [(62, 39), (23, 39)],
                               'type': 'MEDIUM'},
                'NET_229': {   'length': 32,
                               'pins': [(51, 24), (21, 22)],
                               'type': 'MEDIUM'},
                'NET_23': {   'length': 13,
                              'pins': [(64, 3), (73, 7)],
                              'type': 'LOCAL'},
                'NET_230': {   'length': 22,
                               'pins': [(27, 52), (21, 68)],
                               'type': 'MEDIUM'},
                'NET_231': {   'length': 23,
                               'pins': [(71, 23), (80, 37)],
                               'type': 'MEDIUM'},
                'NET_232': {   'length': 41,
                               'pins': [(76, 11), (73, 49)],
                               'type': 'MEDIUM'},
                'NET_233': {   'length': 33,
                               'pins': [(13, 61), (15, 92)],
                               'type': 'MEDIUM'},
                'NET_234': {   'length': 44,
                               'pins': [(74, 36), (31, 37)],
                               'type': 'MEDIUM'},
                'NET_235': {   'length': 37,
                               'pins': [(56, 92), (78, 77)],
                               'type': 'MEDIUM'},
                'NET_236': {   'length': 32,
                               'pins': [(75, 47), (62, 66)],
                               'type': 'MEDIUM'},
                'NET_237': {   'length': 47,
                               'pins': [(36, 50), (42, 9)],
                               'type': 'MEDIUM'},
                'NET_238': {   'length': 59,
                               'pins': [(48, 74), (12, 97)],
                               'type': 'LONG'},
                'NET_239': {   'length': 84,
                               'pins': [(98, 73), (41, 46)],
                               'type': 'LONG'},
                'NET_24': {   'length': 17,
                              'pins': [(37, 31), (22, 33)],
                              'type': 'LOCAL'},
                'NET_240': {   'length': 102,
                               'pins': [(7, 65), (79, 35)],
                               'type': 'LONG'},
                'NET_241': {   'length': 120,
                               'pins': [(25, 24), (73, 96)],
                               'type': 'LONG'},
                'NET_242': {   'length': 88,
                               'pins': [(42, 89), (20, 23)],
                               'type': 'LONG'},
                'NET_243': {   'length': 78,
                               'pins': [(60, 25), (18, 61)],
                               'type': 'LONG'},
                'NET_244': {   'length': 94,
                               'pins': [(52, 30), (14, 86)],
                               'type': 'LONG'},
                'NET_245': {   'length': 60,
                               'pins': [(42, 8), (20, 46)],
                               'type': 'LONG'},
                'NET_246': {   'length': 64,
                               'pins': [(36, 18), (43, 75)],
                               'type': 'LONG'},
                'NET_247': {   'length': 72,
                               'pins': [(92, 45), (54, 11)],
                               'type': 'LONG'},
                'NET_248': {   'length': 71,
                               'pins': [(11, 65), (76, 71)],
                               'type': 'LONG'},
                'NET_249': {   'length': 77,
                               'pins': [(45, 0), (29, 61)],
                               'type': 'LONG'},
                'NET_25': {   'length': 19,
                              'pins': [(20, 53), (2, 54)],
                              'type': 'LOCAL'},
                'NET_26': {   'length': 13,
                              'pins': [(20, 55), (12, 50)],
                              'type': 'LOCAL'},
                'NET_27': {   'length': 12,
                              'pins': [(11, 40), (5, 34)],
                              'type': 'LOCAL'},
                'NET_28': {   'length': 17,
                              'pins': [(64, 86), (74, 79)],
                              'type': 'LOCAL'},
                'NET_29': {   'length': 15,
                              'pins': [(4, 84), (15, 80)],
                              'type': 'LOCAL'},
                'NET_3': {   'length': 20,
                             'pins': [(62, 48), (64, 30)],
                             'type': 'LOCAL'},
                'NET_30': {   'length': 9,
                              'pins': [(95, 21), (99, 26)],
                              'type': 'LOCAL'},
                'NET_31': {   'length': 6,
                              'pins': [(17, 40), (23, 40)],
                              'type': 'LOCAL'},
                'NET_32': {   'length': 19,
                              'pins': [(77, 2), (61, 5)],
                              'type': 'LOCAL'},
                'NET_33': {   'length': 7,
                              'pins': [(48, 0), (52, 3)],
                              'type': 'LOCAL'},
                'NET_34': {   'length': 18,
                              'pins': [(80, 28), (97, 29)],
                              'type': 'LOCAL'},
                'NET_35': {   'length': 9,
                              'pins': [(32, 38), (37, 42)],
                              'type': 'LOCAL'},
                'NET_36': {   'length': 18,
                              'pins': [(85, 43), (69, 41)],
                              'type': 'LOCAL'},
                'NET_37': {   'length': 3,
                              'pins': [(95, 27), (96, 25)],
                              'type': 'LOCAL'},
                'NET_38': {   'length': 5,
                              'pins': [(93, 42), (92, 46)],
                              'type': 'LOCAL'},
                'NET_39': {   'length': 12,
                              'pins': [(64, 81), (73, 84)],
                              'type': 'LOCAL'},
                'NET_4': {   'length': 11,
                             'pins': [(46, 26), (53, 22)],
                             'type': 'LOCAL'},
                'NET_40': {   'length': 8,
                              'pins': [(41, 88), (39, 82)],
                              'type': 'LOCAL'},
                'NET_41': {   'length': 14,
                              'pins': [(19, 63), (33, 63)],
                              'type': 'LOCAL'},
                'NET_42': {   'length': 11,
                              'pins': [(88, 67), (84, 74)],
                              'type': 'LOCAL'},
                'NET_43': {   'length': 19,
                              'pins': [(89, 49), (97, 38)],
                              'type': 'LOCAL'},
                'NET_44': {   'length': 20,
                              'pins': [(35, 66), (18, 69)],
                              'type': 'LOCAL'},
                'NET_45': {   'length': 19,
                              'pins': [(55, 63), (50, 49)],
                              'type': 'LOCAL'},
                'NET_46': {   'length': 14,
                              'pins': [(28, 24), (21, 17)],
                              'type': 'LOCAL'},
                'NET_47': {   'length': 13,
                              'pins': [(74, 17), (79, 9)],
                              'type': 'LOCAL'},
                'NET_48': {   'length': 8,
                              'pins': [(14, 96), (21, 97)],
                              'type': 'LOCAL'},
                'NET_49': {   'length': 16,
                              'pins': [(24, 76), (35, 81)],
                              'type': 'LOCAL'},
                'NET_5': {   'length': 18,
                             'pins': [(74, 26), (80, 38)],
                             'type': 'LOCAL'},
                'NET_50': {   'length': 12,
                              'pins': [(90, 59), (88, 69)],
                              'type': 'LOCAL'},
                'NET_51': {   'length': 20,
                              'pins': [(39, 95), (22, 98)],
                              'type': 'LOCAL'},
                'NET_52': {   'length': 18,
                              'pins': [(6, 83), (20, 87)],
                              'type': 'LOCAL'},
                'NET_53': {   'length': 18,
                              'pins': [(32, 6), (17, 3)],
                              'type': 'LOCAL'},
                'NET_54': {   'length': 19,
                              'pins': [(3, 52), (15, 59)],
                              'type': 'LOCAL'},
                'NET_55': {   'length': 14,
                              'pins': [(84, 34), (71, 33)],
                              'type': 'LOCAL'},
                'NET_56': {   'length': 20,
                              'pins': [(94, 79), (86, 91)],
                              'type': 'LOCAL'},
                'NET_57': {   'length': 6,
                              'pins': [(53, 42), (57, 44)],
                              'type': 'LOCAL'},
                'NET_58': {   'length': 11,
                              'pins': [(63, 96), (73, 97)],
                              'type': 'LOCAL'},
                'NET_59': {   'length': 17,
                              'pins': [(17, 15), (4, 11)],
                              'type': 'LOCAL'},
                'NET_6': {   'length': 13,
                             'pins': [(54, 40), (52, 51)],
                             'type': 'LOCAL'},
                'NET_60': {   'length': 13,
                              'pins': [(5, 82), (18, 82)],
                              'type': 'LOCAL'},
                'NET_61': {   'length': 5,
                              'pins': [(23, 98), (27, 99)],
                              'type': 'LOCAL'},
                'NET_62': {   'length': 18,
                              'pins': [(78, 86), (91, 81)],
                              'type': 'LOCAL'},
                'NET_63': {   'length': 15,
                              'pins': [(83, 52), (91, 45)],
                              'type': 'LOCAL'},
                'NET_64': {   'length': 15,
                              'pins': [(60, 53), (58, 40)],
                              'type': 'LOCAL'},
                'NET_65': {   'length': 16,
                              'pins': [(47, 99), (53, 89)],
                              'type': 'LOCAL'},
                'NET_66': {   'length': 12,
                              'pins': [(99, 22), (88, 21)],
                              'type': 'LOCAL'},
                'NET_67': {   'length': 16,
                              'pins': [(61, 31), (47, 29)],
                              'type': 'LOCAL'},
                'NET_68': {   'length': 10,
                              'pins': [(95, 68), (88, 71)],
                              'type': 'LOCAL'},
                'NET_69': {   'length': 17,
                              'pins': [(39, 6), (26, 2)],
                              'type': 'LOCAL'},
                'NET_7': {   'length': 18,
                             'pins': [(72, 35), (75, 50)],
                             'type': 'LOCAL'},
                'NET_70': {   'length': 9,
                              'pins': [(16, 3), (19, 9)],
                              'type': 'LOCAL'},
                'NET_71': {   'length': 6,
                              'pins': [(11, 17), (16, 18)],
                              'type': 'LOCAL'},
                'NET_72': {   'length': 13,
                              'pins': [(26, 33), (38, 32)],
                              'type': 'LOCAL'},
                'NET_73': {   'length': 20,
                              'pins': [(26, 81), (10, 85)],
                              'type': 'LOCAL'},
                'NET_74': {   'length': 17,
                              'pins': [(7, 57), (5, 42)],
                              'type': 'LOCAL'},
                'NET_75': {   'length': 14,
                              'pins': [(76, 9), (77, 22)],
                              'type': 'LOCAL'},
                'NET_76': {   'length': 20,
                              'pins': [(25, 40), (31, 54)],
                              'type': 'LOCAL'},
                'NET_77': {   'length': 5,
                              'pins': [(23, 38), (21, 35)],
                              'type': 'LOCAL'},
                'NET_78': {   'length': 14,
                              'pins': [(69, 89), (56, 90)],
                              'type': 'LOCAL'},
                'NET_79': {   'length': 14,
                              'pins': [(1, 57), (14, 58)],
                              'type': 'LOCAL'},
                'NET_8': {   'length': 19,
                             'pins': [(6, 44), (21, 48)],
                             'type': 'LOCAL'},
                'NET_80': {   'length': 15,
                              'pins': [(84, 79), (95, 83)],
                              'type': 'LOCAL'},
                'NET_81': {   'length': 15,
                              'pins': [(81, 87), (94, 89)],
                              'type': 'LOCAL'},
                'NET_82': {   'length': 15,
                              'pins': [(19, 45), (13, 54)],
                              'type': 'LOCAL'},
                'NET_83': {   'length': 20,
                              'pins': [(73, 79), (83, 69)],
                              'type': 'LOCAL'},
                'NET_84': {   'length': 20,
                              'pins': [(71, 8), (58, 15)],
                              'type': 'LOCAL'},
                'NET_85': {   'length': 4,
                              'pins': [(77, 40), (74, 41)],
                              'type': 'LOCAL'},
                'NET_86': {   'length': 18,
                              'pins': [(68, 77), (85, 78)],
                              'type': 'LOCAL'},
                'NET_87': {   'length': 19,
                              'pins': [(91, 85), (82, 75)],
                              'type': 'LOCAL'},
                'NET_88': {   'length': 3,
                              'pins': [(46, 89), (48, 90)],
                              'type': 'LOCAL'},
                'NET_89': {   'length': 9,
                              'pins': [(98, 69), (95, 75)],
                              'type': 'LOCAL'},
                'NET_9': {   'length': 15,
                             'pins': [(39, 0), (34, 10)],
                             'type': 'LOCAL'},
                'NET_90': {   'length': 19,
                              'pins': [(52, 59), (34, 58)],
                              'type': 'LOCAL'},
                'NET_91': {   'length': 15,
                              'pins': [(50, 37), (54, 26)],
                              'type': 'LOCAL'},
                'NET_92': {   'length': 15,
                              'pins': [(68, 26), (67, 40)],
                              'type': 'LOCAL'},
                'NET_93': {   'length': 11,
                              'pins': [(1, 3), (12, 3)],
                              'type': 'LOCAL'},
                'NET_94': {   'length': 18,
                              'pins': [(93, 24), (88, 37)],
                              'type': 'LOCAL'},
                'NET_95': {   'length': 17,
                              'pins': [(82, 4), (82, 21)],
                              'type': 'LOCAL'},
                'NET_96': {   'length': 17,
                              'pins': [(66, 2), (56, 9)],
                              'type': 'LOCAL'},
                'NET_97': {   'length': 17,
                              'pins': [(34, 16), (20, 19)],
                              'type': 'LOCAL'},
                'NET_98': {   'length': 16,
                              'pins': [(53, 14), (64, 19)],
                              'type': 'LOCAL'},
                'NET_99': {   'length': 13,
                              'pins': [(90, 35), (83, 29)],
                              'type': 'LOCAL'}}}
