# Auto-generated router-visible netlist
# No optimal metadata included

data = {   'grid_size': 100,
    'nets': {   'NET_0': {   'length': 4,
                             'pins': [(0, 0), (1, 3)],
                             'type': 'MEDIUM'},
                'NET_1': {   'length': 2,
                             'pins': [(7, 1), (8, 2)],
                             'type': 'MEDIUM'},
                'NET_10': {   'length': 3,
                              'pins': [(50, 1), (51, 3)],
                              'type': 'MEDIUM'},
                'NET_100': {   'length': 3,
                               'pins': [(0, 26), (1, 28)],
                               'type': 'MEDIUM'},
                'NET_101': {   'length': 6,
                               'pins': [(5, 25), (8, 28)],
                               'type': 'MEDIUM'},
                'NET_102': {   'length': 3,
                               'pins': [(11, 26), (12, 28)],
                               'type': 'MEDIUM'},
                'NET_103': {   'length': 5,
                               'pins': [(17, 26), (19, 29)],
                               'type': 'MEDIUM'},
                'NET_104': {   'length': 3,
                               'pins': [(22, 26), (23, 28)],
                               'type': 'MEDIUM'},
                'NET_105': {   'length': 3,
                               'pins': [(26, 25), (28, 26)],
                               'type': 'MEDIUM'},
                'NET_106': {   'length': 4,
                               'pins': [(31, 26), (33, 28)],
                               'type': 'MEDIUM'},
                'NET_107': {   'length': 2,
                               'pins': [(38, 27), (39, 28)],
                               'type': 'MEDIUM'},
                'NET_108': {   'length': 2,
                               'pins': [(42, 27), (43, 28)],
                               'type': 'MEDIUM'},
                'NET_109': {   'length': 3,
                               'pins': [(46, 27), (48, 28)],
                               'type': 'MEDIUM'},
                'NET_11': {   'length': 2,
                              'pins': [(57, 1), (58, 2)],
                              'type': 'MEDIUM'},
                'NET_110': {   'length': 4,
                               'pins': [(52, 25), (53, 28)],
                               'type': 'MEDIUM'},
                'NET_111': {   'length': 4,
                               'pins': [(56, 26), (58, 28)],
                               'type': 'MEDIUM'},
                'NET_112': {   'length': 2,
                               'pins': [(61, 27), (62, 28)],
                               'type': 'MEDIUM'},
                'NET_113': {   'length': 4,
                               'pins': [(65, 26), (68, 27)],
                               'type': 'MEDIUM'},
                'NET_114': {   'length': 3,
                               'pins': [(71, 26), (72, 28)],
                               'type': 'MEDIUM'},
                'NET_115': {   'length': 2,
                               'pins': [(78, 28), (79, 29)],
                               'type': 'MEDIUM'},
                'NET_116': {   'length': 3,
                               'pins': [(81, 26), (82, 28)],
                               'type': 'MEDIUM'},
                'NET_117': {   'length': 4,
                               'pins': [(85, 26), (87, 28)],
                               'type': 'MEDIUM'},
                'NET_118': {   'length': 3,
                               'pins': [(92, 26), (93, 28)],
                               'type': 'MEDIUM'},
                'NET_119': {   'length': 5,
                               'pins': [(95, 25), (98, 27)],
                               'type': 'MEDIUM'},
                'NET_12': {   'length': 2,
                              'pins': [(62, 2), (63, 3)],
                              'type': 'MEDIUM'},
                'NET_120': {   'length': 2,
                               'pins': [(2, 31), (3, 32)],
                               'type': 'MEDIUM'},
                'NET_121': {   'length': 5,
                               'pins': [(5, 32), (8, 34)],
                               'type': 'MEDIUM'},
                'NET_122': {   'length': 3,
                               'pins': [(10, 32), (12, 33)],
                               'type': 'MEDIUM'},
                'NET_123': {   'length': 2,
                               'pins': [(18, 32), (19, 33)],
                               'type': 'MEDIUM'},
                'NET_124': {   'length': 2,
                               'pins': [(20, 32), (21, 33)],
                               'type': 'MEDIUM'},
                'NET_125': {   'length': 2,
                               'pins': [(27, 31), (28, 32)],
                               'type': 'MEDIUM'},
                'NET_126': {   'length': 4,
                               'pins': [(30, 33), (33, 34)],
                               'type': 'MEDIUM'},
                'NET_127': {   'length': 5,
                               'pins': [(35, 32), (38, 34)],
                               'type': 'MEDIUM'},
                'NET_128': {   'length': 2,
                               'pins': [(43, 33), (44, 34)],
                               'type': 'MEDIUM'},
                'NET_129': {   'length': 3,
                               'pins': [(45, 32), (47, 33)],
                               'type': 'MEDIUM'},
                'NET_13': {   'length': 2,
                              'pins': [(68, 3), (69, 4)],
                              'type': 'MEDIUM'},
                'NET_130': {   'length': 2,
                               'pins': [(51, 32), (52, 33)],
                               'type': 'MEDIUM'},
                'NET_131': {   'length': 3,
                               'pins': [(55, 33), (57, 34)],
                               'type': 'MEDIUM'},
                'NET_132': {   'length': 6,
                               'pins': [(60, 30), (63, 33)],
                               'type': 'MEDIUM'},
                'NET_133': {   'length': 4,
                               'pins': [(66, 31), (69, 32)],
                               'type': 'MEDIUM'},
                'NET_134': {   'length': 5,
                               'pins': [(70, 30), (74, 31)],
                               'type': 'MEDIUM'},
                'NET_135': {   'length': 3,
                               'pins': [(75, 32), (77, 33)],
                               'type': 'MEDIUM'},
                'NET_136': {   'length': 2,
                               'pins': [(82, 31), (83, 32)],
                               'type': 'MEDIUM'},
                'NET_137': {   'length': 2,
                               'pins': [(87, 32), (88, 33)],
                               'type': 'MEDIUM'},
                'NET_138': {   'length': 4,
                               'pins': [(91, 31), (93, 33)],
                               'type': 'MEDIUM'},
                'NET_139': {   'length': 6,
                               'pins': [(95, 32), (99, 34)],
                               'type': 'MEDIUM'},
                'NET_14': {   'length': 2,
                              'pins': [(72, 0), (73, 1)],
                              'type': 'MEDIUM'},
                'NET_140': {   'length': 4,
                               'pins': [(0, 37), (3, 38)],
                               'type': 'MEDIUM'},
                'NET_141': {   'length': 2,
                               'pins': [(7, 35), (8, 36)],
                               'type': 'MEDIUM'},
                'NET_142': {   'length': 5,
                               'pins': [(10, 38), (14, 39)],
                               'type': 'MEDIUM'},
                'NET_143': {   'length': 2,
                               'pins': [(17, 37), (18, 38)],
                               'type': 'MEDIUM'},
                'NET_144': {   'length': 2,
                               'pins': [(22, 37), (23, 38)],
                               'type': 'MEDIUM'},
                'NET_145': {   'length': 4,
                               'pins': [(25, 35), (26, 38)],
                               'type': 'MEDIUM'},
                'NET_146': {   'length': 2,
                               'pins': [(32, 37), (33, 38)],
                               'type': 'MEDIUM'},
                'NET_147': {   'length': 5,
                               'pins': [(35, 36), (38, 38)],
                               'type': 'MEDIUM'},
                'NET_148': {   'length': 2,
                               'pins': [(43, 38), (44, 39)],
                               'type': 'MEDIUM'},
                'NET_149': {   'length': 6,
                               'pins': [(45, 35), (48, 38)],
                               'type': 'MEDIUM'},
                'NET_15': {   'length': 2,
                              'pins': [(77, 3), (78, 4)],
                              'type': 'MEDIUM'},
                'NET_150': {   'length': 3,
                               'pins': [(51, 36), (53, 37)],
                               'type': 'MEDIUM'},
                'NET_151': {   'length': 3,
                               'pins': [(58, 35), (59, 37)],
                               'type': 'MEDIUM'},
                'NET_152': {   'length': 2,
                               'pins': [(60, 36), (61, 37)],
                               'type': 'MEDIUM'},
                'NET_153': {   'length': 6,
                               'pins': [(65, 35), (68, 38)],
                               'type': 'MEDIUM'},
                'NET_154': {   'length': 3,
                               'pins': [(72, 38), (74, 39)],
                               'type': 'MEDIUM'},
                'NET_155': {   'length': 2,
                               'pins': [(78, 38), (79, 39)],
                               'type': 'MEDIUM'},
                'NET_156': {   'length': 3,
                               'pins': [(81, 36), (83, 37)],
                               'type': 'MEDIUM'},
                'NET_157': {   'length': 4,
                               'pins': [(87, 37), (89, 39)],
                               'type': 'MEDIUM'},
                'NET_158': {   'length': 3,
                               'pins': [(92, 38), (94, 39)],
                               'type': 'MEDIUM'},
                'NET_159': {   'length': 4,
                               'pins': [(96, 35), (97, 38)],
                               'type': 'MEDIUM'},
                'NET_16': {   'length': 2,
                              'pins': [(82, 0), (83, 1)],
                              'type': 'MEDIUM'},
                'NET_160': {   'length': 3,
                               'pins': [(2, 41), (3, 43)],
                               'type': 'MEDIUM'},
                'NET_161': {   'length': 4,
                               'pins': [(5, 40), (7, 42)],
                               'type': 'MEDIUM'},
                'NET_162': {   'length': 7,
                               'pins': [(10, 40), (14, 43)],
                               'type': 'MEDIUM'},
                'NET_163': {   'length': 4,
                               'pins': [(15, 40), (16, 43)],
                               'type': 'MEDIUM'},
                'NET_164': {   'length': 3,
                               'pins': [(20, 41), (22, 42)],
                               'type': 'MEDIUM'},
                'NET_165': {   'length': 4,
                               'pins': [(28, 41), (29, 44)],
                               'type': 'MEDIUM'},
                'NET_166': {   'length': 4,
                               'pins': [(31, 41), (34, 42)],
                               'type': 'MEDIUM'},
                'NET_167': {   'length': 2,
                               'pins': [(35, 40), (36, 41)],
                               'type': 'MEDIUM'},
                'NET_168': {   'length': 4,
                               'pins': [(42, 42), (44, 44)],
                               'type': 'MEDIUM'},
                'NET_169': {   'length': 2,
                               'pins': [(47, 42), (48, 43)],
                               'type': 'MEDIUM'},
                'NET_17': {   'length': 3,
                              'pins': [(85, 2), (87, 3)],
                              'type': 'MEDIUM'},
                'NET_170': {   'length': 4,
                               'pins': [(51, 41), (54, 42)],
                               'type': 'MEDIUM'},
                'NET_171': {   'length': 3,
                               'pins': [(57, 41), (58, 43)],
                               'type': 'MEDIUM'},
                'NET_172': {   'length': 2,
                               'pins': [(61, 41), (62, 42)],
                               'type': 'MEDIUM'},
                'NET_173': {   'length': 3,
                               'pins': [(67, 43), (69, 44)],
                               'type': 'MEDIUM'},
                'NET_174': {   'length': 3,
                               'pins': [(71, 42), (73, 43)],
                               'type': 'MEDIUM'},
                'NET_175': {   'length': 4,
                               'pins': [(76, 40), (78, 42)],
                               'type': 'MEDIUM'},
                'NET_176': {   'length': 4,
                               'pins': [(83, 40), (84, 43)],
                               'type': 'MEDIUM'},
                'NET_177': {   'length': 4,
                               'pins': [(85, 43), (88, 44)],
                               'type': 'MEDIUM'},
                'NET_178': {   'length': 2,
                               'pins': [(92, 42), (93, 43)],
                               'type': 'MEDIUM'},
                'NET_179': {   'length': 2,
                               'pins': [(98, 40), (99, 41)],
                               'type': 'MEDIUM'},
                'NET_18': {   'length': 4,
                              'pins': [(93, 1), (94, 4)],
                              'type': 'MEDIUM'},
                'NET_180': {   'length': 2,
                               'pins': [(2, 46), (3, 47)],
                               'type': 'MEDIUM'},
                'NET_181': {   'length': 3,
                               'pins': [(7, 46), (8, 48)],
                               'type': 'MEDIUM'},
                'NET_182': {   'length': 4,
                               'pins': [(10, 46), (12, 48)],
                               'type': 'MEDIUM'},
                'NET_183': {   'length': 2,
                               'pins': [(17, 46), (18, 47)],
                               'type': 'MEDIUM'},
                'NET_184': {   'length': 4,
                               'pins': [(21, 45), (22, 48)],
                               'type': 'MEDIUM'},
                'NET_185': {   'length': 3,
                               'pins': [(27, 48), (29, 49)],
                               'type': 'MEDIUM'},
                'NET_186': {   'length': 3,
                               'pins': [(31, 48), (33, 49)],
                               'type': 'MEDIUM'},
                'NET_187': {   'length': 3,
                               'pins': [(38, 46), (39, 48)],
                               'type': 'MEDIUM'},
                'NET_188': {   'length': 3,
                               'pins': [(40, 46), (41, 48)],
                               'type': 'MEDIUM'},
                'NET_189': {   'length': 2,
                               'pins': [(48, 48), (49, 49)],
                               'type': 'MEDIUM'},
                'NET_19': {   'length': 3,
                              'pins': [(98, 1), (99, 3)],
                              'type': 'MEDIUM'},
                'NET_190': {   'length': 2,
                               'pins': [(52, 47), (53, 48)],
                               'type': 'MEDIUM'},
                'NET_191': {   'length': 4,
                               'pins': [(57, 45), (58, 48)],
                               'type': 'MEDIUM'},
                'NET_192': {   'length': 2,
                               'pins': [(63, 48), (64, 49)],
                               'type': 'MEDIUM'},
                'NET_193': {   'length': 5,
                               'pins': [(65, 45), (68, 47)],
                               'type': 'MEDIUM'},
                'NET_194': {   'length': 2,
                               'pins': [(73, 47), (74, 48)],
                               'type': 'MEDIUM'},
                'NET_195': {   'length': 3,
                               'pins': [(77, 46), (78, 48)],
                               'type': 'MEDIUM'},
                'NET_196': {   'length': 3,
                               'pins': [(80, 47), (82, 48)],
                               'type': 'MEDIUM'},
                'NET_197': {   'length': 5,
                               'pins': [(85, 45), (88, 47)],
                               'type': 'MEDIUM'},
                'NET_198': {   'length': 2,
                               'pins': [(93, 48), (94, 49)],
                               'type': 'MEDIUM'},
                'NET_199': {   'length': 3,
                               'pins': [(98, 47), (99, 49)],
                               'type': 'MEDIUM'},
                'NET_2': {   'length': 2,
                             'pins': [(12, 1), (13, 2)],
                             'type': 'MEDIUM'},
                'NET_20': {   'length': 2,
                              'pins': [(3, 8), (4, 9)],
                              'type': 'MEDIUM'},
                'NET_200': {   'length': 2,
                               'pins': [(3, 52), (4, 53)],
                               'type': 'MEDIUM'},
                'NET_201': {   'length': 5,
                               'pins': [(5, 51), (8, 53)],
                               'type': 'MEDIUM'},
                'NET_202': {   'length': 2,
                               'pins': [(11, 51), (12, 52)],
                               'type': 'MEDIUM'},
                'NET_203': {   'length': 5,
                               'pins': [(17, 50), (19, 53)],
                               'type': 'MEDIUM'},
                'NET_204': {   'length': 4,
                               'pins': [(20, 52), (23, 53)],
                               'type': 'MEDIUM'},
                'NET_205': {   'length': 2,
                               'pins': [(27, 52), (28, 53)],
                               'type': 'MEDIUM'},
                'NET_206': {   'length': 5,
                               'pins': [(30, 50), (31, 54)],
                               'type': 'MEDIUM'},
                'NET_207': {   'length': 5,
                               'pins': [(36, 50), (38, 53)],
                               'type': 'MEDIUM'},
                'NET_208': {   'length': 4,
                               'pins': [(41, 50), (44, 51)],
                               'type': 'MEDIUM'},
                'NET_209': {   'length': 4,
                               'pins': [(46, 52), (48, 54)],
                               'type': 'MEDIUM'},
                'NET_21': {   'length': 6,
                              'pins': [(6, 5), (9, 8)],
                              'type': 'MEDIUM'},
                'NET_210': {   'length': 2,
                               'pins': [(52, 52), (53, 53)],
                               'type': 'MEDIUM'},
                'NET_211': {   'length': 3,
                               'pins': [(55, 52), (57, 53)],
                               'type': 'MEDIUM'},
                'NET_212': {   'length': 3,
                               'pins': [(60, 51), (62, 52)],
                               'type': 'MEDIUM'},
                'NET_213': {   'length': 2,
                               'pins': [(68, 50), (69, 51)],
                               'type': 'MEDIUM'},
                'NET_214': {   'length': 4,
                               'pins': [(71, 52), (73, 54)],
                               'type': 'MEDIUM'},
                'NET_215': {   'length': 5,
                               'pins': [(75, 50), (76, 54)],
                               'type': 'MEDIUM'},
                'NET_216': {   'length': 3,
                               'pins': [(81, 51), (83, 52)],
                               'type': 'MEDIUM'},
                'NET_217': {   'length': 4,
                               'pins': [(85, 52), (88, 53)],
                               'type': 'MEDIUM'},
                'NET_218': {   'length': 3,
                               'pins': [(92, 53), (94, 54)],
                               'type': 'MEDIUM'},
                'NET_219': {   'length': 3,
                               'pins': [(97, 52), (99, 53)],
                               'type': 'MEDIUM'},
                'NET_22': {   'length': 3,
                              'pins': [(10, 6), (12, 7)],
                              'type': 'MEDIUM'},
                'NET_220': {   'length': 6,
                               'pins': [(0, 55), (3, 58)],
                               'type': 'MEDIUM'},
                'NET_221': {   'length': 2,
                               'pins': [(6, 56), (7, 57)],
                               'type': 'MEDIUM'},
                'NET_222': {   'length': 2,
                               'pins': [(11, 56), (12, 57)],
                               'type': 'MEDIUM'},
                'NET_223': {   'length': 2,
                               'pins': [(16, 55), (17, 56)],
                               'type': 'MEDIUM'},
                'NET_224': {   'length': 2,
                               'pins': [(23, 58), (24, 59)],
                               'type': 'MEDIUM'},
                'NET_225': {   'length': 4,
                               'pins': [(27, 57), (29, 59)],
                               'type': 'MEDIUM'},
                'NET_226': {   'length': 5,
                               'pins': [(32, 56), (34, 59)],
                               'type': 'MEDIUM'},
                'NET_227': {   'length': 7,
                               'pins': [(35, 55), (39, 58)],
                               'type': 'MEDIUM'},
                'NET_228': {   'length': 2,
                               'pins': [(43, 57), (44, 58)],
                               'type': 'MEDIUM'},
                'NET_229': {   'length': 2,
                               'pins': [(45, 58), (46, 59)],
                               'type': 'MEDIUM'},
                'NET_23': {   'length': 3,
                              'pins': [(15, 7), (17, 8)],
                              'type': 'MEDIUM'},
                'NET_230': {   'length': 2,
                               'pins': [(50, 56), (51, 57)],
                               'type': 'MEDIUM'},
                'NET_231': {   'length': 3,
                               'pins': [(56, 55), (58, 56)],
                               'type': 'MEDIUM'},
                'NET_232': {   'length': 2,
                               'pins': [(61, 55), (62, 56)],
                               'type': 'MEDIUM'},
                'NET_233': {   'length': 4,
                               'pins': [(67, 57), (69, 59)],
                               'type': 'MEDIUM'},
                'NET_234': {   'length': 5,
                               'pins': [(70, 55), (72, 58)],
                               'type': 'MEDIUM'},
                'NET_235': {   'length': 4,
                               'pins': [(76, 58), (79, 59)],
                               'type': 'MEDIUM'},
                'NET_236': {   'length': 3,
                               'pins': [(82, 55), (83, 57)],
                               'type': 'MEDIUM'},
                'NET_237': {   'length': 3,
                               'pins': [(87, 55), (89, 56)],
                               'type': 'MEDIUM'},
                'NET_238': {   'length': 3,
                               'pins': [(90, 57), (92, 58)],
                               'type': 'MEDIUM'},
                'NET_239': {   'length': 3,
                               'pins': [(97, 55), (99, 56)],
                               'type': 'MEDIUM'},
                'NET_24': {   'length': 2,
                              'pins': [(22, 7), (23, 8)],
                              'type': 'MEDIUM'},
                'NET_240': {   'length': 4,
                               'pins': [(0, 60), (3, 61)],
                               'type': 'MEDIUM'},
                'NET_241': {   'length': 2,
                               'pins': [(6, 61), (7, 62)],
                               'type': 'MEDIUM'},
                'NET_242': {   'length': 4,
                               'pins': [(13, 61), (14, 64)],
                               'type': 'MEDIUM'},
                'NET_243': {   'length': 3,
                               'pins': [(16, 61), (18, 62)],
                               'type': 'MEDIUM'},
                'NET_244': {   'length': 4,
                               'pins': [(20, 62), (23, 63)],
                               'type': 'MEDIUM'},
                'NET_245': {   'length': 3,
                               'pins': [(28, 60), (29, 62)],
                               'type': 'MEDIUM'},
                'NET_246': {   'length': 4,
                               'pins': [(30, 60), (31, 63)],
                               'type': 'MEDIUM'},
                'NET_247': {   'length': 4,
                               'pins': [(36, 63), (39, 64)],
                               'type': 'MEDIUM'},
                'NET_248': {   'length': 3,
                               'pins': [(42, 61), (44, 62)],
                               'type': 'MEDIUM'},
                'NET_249': {   'length': 4,
                               'pins': [(46, 63), (49, 64)],
                               'type': 'MEDIUM'},
                'NET_25': {   'length': 3,
                              'pins': [(26, 7), (28, 8)],
                              'type': 'MEDIUM'},
                'NET_250': {   'length': 3,
                               'pins': [(50, 63), (52, 64)],
                               'type': 'MEDIUM'},
                'NET_251': {   'length': 2,
                               'pins': [(57, 62), (58, 63)],
                               'type': 'MEDIUM'},
                'NET_252': {   'length': 2,
                               'pins': [(61, 62), (62, 63)],
                               'type': 'MEDIUM'},
                'NET_253': {   'length': 3,
                               'pins': [(65, 62), (67, 63)],
                               'type': 'MEDIUM'},
                'NET_254': {   'length': 3,
                               'pins': [(70, 60), (72, 61)],
                               'type': 'MEDIUM'},
                'NET_255': {   'length': 2,
                               'pins': [(78, 63), (79, 64)],
                               'type': 'MEDIUM'},
                'NET_256': {   'length': 4,
                               'pins': [(83, 61), (84, 64)],
                               'type': 'MEDIUM'},
                'NET_257': {   'length': 2,
                               'pins': [(87, 63), (88, 64)],
                               'type': 'MEDIUM'},
                'NET_258': {   'length': 5,
                               'pins': [(91, 61), (93, 64)],
                               'type': 'MEDIUM'},
                'NET_259': {   'length': 3,
                               'pins': [(97, 60), (98, 62)],
                               'type': 'MEDIUM'},
                'NET_26': {   'length': 2,
                              'pins': [(32, 8), (33, 9)],
                              'type': 'MEDIUM'},
                'NET_260': {   'length': 2,
                               'pins': [(0, 67), (1, 68)],
                               'type': 'MEDIUM'},
                'NET_261': {   'length': 3,
                               'pins': [(5, 66), (6, 68)],
                               'type': 'MEDIUM'},
                'NET_262': {   'length': 4,
                               'pins': [(12, 65), (13, 68)],
                               'type': 'MEDIUM'},
                'NET_263': {   'length': 3,
                               'pins': [(16, 67), (17, 69)],
                               'type': 'MEDIUM'},
                'NET_264': {   'length': 4,
                               'pins': [(21, 67), (24, 68)],
                               'type': 'MEDIUM'},
                'NET_265': {   'length': 2,
                               'pins': [(27, 67), (28, 68)],
                               'type': 'MEDIUM'},
                'NET_266': {   'length': 5,
                               'pins': [(30, 66), (33, 68)],
                               'type': 'MEDIUM'},
                'NET_267': {   'length': 4,
                               'pins': [(35, 65), (36, 68)],
                               'type': 'MEDIUM'},
                'NET_268': {   'length': 2,
                               'pins': [(42, 67), (43, 68)],
                               'type': 'MEDIUM'},
                'NET_269': {   'length': 2,
                               'pins': [(48, 66), (49, 67)],
                               'type': 'MEDIUM'},
                'NET_27': {   'length': 3,
                              'pins': [(35, 6), (37, 7)],
                              'type': 'MEDIUM'},
                'NET_270': {   'length': 3,
                               'pins': [(50, 65), (52, 66)],
                               'type': 'MEDIUM'},
                'NET_271': {   'length': 5,
                               'pins': [(56, 65), (58, 68)],
                               'type': 'MEDIUM'},
                'NET_272': {   'length': 3,
                               'pins': [(61, 67), (63, 68)],
                               'type': 'MEDIUM'},
                'NET_273': {   'length': 4,
                               'pins': [(66, 68), (69, 69)],
                               'type': 'MEDIUM'},
                'NET_274': {   'length': 4,
                               'pins': [(71, 65), (72, 68)],
                               'type': 'MEDIUM'},
                'NET_275': {   'length': 5,
                               'pins': [(75, 68), (79, 69)],
                               'type': 'MEDIUM'},
                'NET_276': {   'length': 3,
                               'pins': [(81, 67), (82, 69)],
                               'type': 'MEDIUM'},
                'NET_277': {   'length': 2,
                               'pins': [(85, 67), (86, 68)],
                               'type': 'MEDIUM'},
                'NET_278': {   'length': 2,
                               'pins': [(92, 65), (93, 66)],
                               'type': 'MEDIUM'},
                'NET_279': {   'length': 2,
                               'pins': [(97, 66), (98, 67)],
                               'type': 'MEDIUM'},
                'NET_28': {   'length': 3,
                              'pins': [(41, 6), (43, 7)],
                              'type': 'MEDIUM'},
                'NET_280': {   'length': 3,
                               'pins': [(0, 71), (2, 72)],
                               'type': 'MEDIUM'},
                'NET_281': {   'length': 4,
                               'pins': [(5, 71), (7, 73)],
                               'type': 'MEDIUM'},
                'NET_282': {   'length': 3,
                               'pins': [(13, 72), (14, 74)],
                               'type': 'MEDIUM'},
                'NET_283': {   'length': 3,
                               'pins': [(17, 71), (18, 73)],
                               'type': 'MEDIUM'},
                'NET_284': {   'length': 4,
                               'pins': [(20, 70), (21, 73)],
                               'type': 'MEDIUM'},
                'NET_285': {   'length': 2,
                               'pins': [(28, 70), (29, 71)],
                               'type': 'MEDIUM'},
                'NET_286': {   'length': 2,
                               'pins': [(32, 72), (33, 73)],
                               'type': 'MEDIUM'},
                'NET_287': {   'length': 5,
                               'pins': [(35, 71), (38, 73)],
                               'type': 'MEDIUM'},
                'NET_288': {   'length': 2,
                               'pins': [(42, 72), (43, 73)],
                               'type': 'MEDIUM'},
                'NET_289': {   'length': 2,
                               'pins': [(48, 73), (49, 74)],
                               'type': 'MEDIUM'},
                'NET_29': {   'length': 3,
                              'pins': [(47, 7), (49, 8)],
                              'type': 'MEDIUM'},
                'NET_290': {   'length': 4,
                               'pins': [(50, 70), (53, 71)],
                               'type': 'MEDIUM'},
                'NET_291': {   'length': 4,
                               'pins': [(56, 70), (57, 73)],
                               'type': 'MEDIUM'},
                'NET_292': {   'length': 2,
                               'pins': [(62, 71), (63, 72)],
                               'type': 'MEDIUM'},
                'NET_293': {   'length': 2,
                               'pins': [(65, 71), (66, 72)],
                               'type': 'MEDIUM'},
                'NET_294': {   'length': 7,
                               'pins': [(71, 70), (74, 74)],
                               'type': 'MEDIUM'},
                'NET_295': {   'length': 2,
                               'pins': [(77, 72), (78, 73)],
                               'type': 'MEDIUM'},
                'NET_296': {   'length': 2,
                               'pins': [(82, 72), (83, 73)],
                               'type': 'MEDIUM'},
                'NET_297': {   'length': 3,
                               'pins': [(86, 70), (87, 72)],
                               'type': 'MEDIUM'},
                'NET_298': {   'length': 5,
                               'pins': [(90, 72), (94, 73)],
                               'type': 'MEDIUM'},
                'NET_299': {   'length': 4,
                               'pins': [(95, 73), (98, 74)],
                               'type': 'MEDIUM'},
                'NET_3': {   'length': 4,
                             'pins': [(18, 1), (19, 4)],
                             'type': 'MEDIUM'},
                'NET_30': {   'length': 4,
                              'pins': [(52, 5), (53, 8)],
                              'type': 'MEDIUM'},
                'NET_300': {   'length': 5,
                               'pins': [(1, 75), (3, 78)],
                               'type': 'MEDIUM'},
                'NET_301': {   'length': 2,
                               'pins': [(7, 78), (8, 79)],
                               'type': 'MEDIUM'},
                'NET_302': {   'length': 2,
                               'pins': [(12, 77), (13, 78)],
                               'type': 'MEDIUM'},
                'NET_303': {   'length': 3,
                               'pins': [(15, 75), (17, 76)],
                               'type': 'MEDIUM'},
                'NET_304': {   'length': 3,
                               'pins': [(20, 77), (22, 78)],
                               'type': 'MEDIUM'},
                'NET_305': {   'length': 2,
                               'pins': [(28, 78), (29, 79)],
                               'type': 'MEDIUM'},
                'NET_306': {   'length': 2,
                               'pins': [(32, 77), (33, 78)],
                               'type': 'MEDIUM'},
                'NET_307': {   'length': 5,
                               'pins': [(35, 75), (37, 78)],
                               'type': 'MEDIUM'},
                'NET_308': {   'length': 3,
                               'pins': [(41, 76), (42, 78)],
                               'type': 'MEDIUM'},
                'NET_309': {   'length': 3,
                               'pins': [(47, 75), (48, 77)],
                               'type': 'MEDIUM'},
                'NET_31': {   'length': 4,
                              'pins': [(56, 5), (57, 8)],
                              'type': 'MEDIUM'},
                'NET_310': {   'length': 4,
                               'pins': [(51, 76), (53, 78)],
                               'type': 'MEDIUM'},
                'NET_311': {   'length': 2,
                               'pins': [(55, 77), (56, 78)],
                               'type': 'MEDIUM'},
                'NET_312': {   'length': 4,
                               'pins': [(62, 76), (64, 78)],
                               'type': 'MEDIUM'},
                'NET_313': {   'length': 2,
                               'pins': [(65, 77), (66, 78)],
                               'type': 'MEDIUM'},
                'NET_314': {   'length': 3,
                               'pins': [(71, 78), (73, 79)],
                               'type': 'MEDIUM'},
                'NET_315': {   'length': 2,
                               'pins': [(78, 78), (79, 79)],
                               'type': 'MEDIUM'},
                'NET_316': {   'length': 7,
                               'pins': [(81, 75), (84, 79)],
                               'type': 'MEDIUM'},
                'NET_317': {   'length': 4,
                               'pins': [(87, 77), (89, 79)],
                               'type': 'MEDIUM'},
                'NET_318': {   'length': 4,
                               'pins': [(91, 76), (93, 78)],
                               'type': 'MEDIUM'},
                'NET_319': {   'length': 2,
                               'pins': [(97, 77), (98, 78)],
                               'type': 'MEDIUM'},
                'NET_32': {   'length': 3,
                              'pins': [(61, 7), (63, 8)],
                              'type': 'MEDIUM'},
                'NET_320': {   'length': 4,
                               'pins': [(3, 81), (4, 84)],
                               'type': 'MEDIUM'},
                'NET_321': {   'length': 3,
                               'pins': [(7, 83), (9, 84)],
                               'type': 'MEDIUM'},
                'NET_322': {   'length': 2,
                               'pins': [(10, 80), (11, 81)],
                               'type': 'MEDIUM'},
                'NET_323': {   'length': 4,
                               'pins': [(15, 83), (18, 84)],
                               'type': 'MEDIUM'},
                'NET_324': {   'length': 4,
                               'pins': [(20, 80), (21, 83)],
                               'type': 'MEDIUM'},
                'NET_325': {   'length': 3,
                               'pins': [(26, 83), (28, 84)],
                               'type': 'MEDIUM'},
                'NET_326': {   'length': 3,
                               'pins': [(32, 81), (33, 83)],
                               'type': 'MEDIUM'},
                'NET_327': {   'length': 2,
                               'pins': [(37, 82), (38, 83)],
                               'type': 'MEDIUM'},
                'NET_328': {   'length': 5,
                               'pins': [(41, 80), (42, 84)],
                               'type': 'MEDIUM'},
                'NET_329': {   'length': 3,
                               'pins': [(48, 80), (49, 82)],
                               'type': 'MEDIUM'},
                'NET_33': {   'length': 5,
                              'pins': [(66, 7), (69, 9)],
                              'type': 'MEDIUM'},
                'NET_330': {   'length': 6,
                               'pins': [(50, 80), (53, 83)],
                               'type': 'MEDIUM'},
                'NET_331': {   'length': 5,
                               'pins': [(55, 83), (59, 84)],
                               'type': 'MEDIUM'},
                'NET_332': {   'length': 4,
                               'pins': [(60, 82), (62, 84)],
                               'type': 'MEDIUM'},
                'NET_333': {   'length': 2,
                               'pins': [(65, 82), (66, 83)],
                               'type': 'MEDIUM'},
                'NET_334': {   'length': 6,
                               'pins': [(71, 81), (74, 84)],
                               'type': 'MEDIUM'},
                'NET_335': {   'length': 3,
                               'pins': [(76, 83), (78, 84)],
                               'type': 'MEDIUM'},
                'NET_336': {   'length': 2,
                               'pins': [(82, 82), (83, 83)],
                               'type': 'MEDIUM'},
                'NET_337': {   'length': 4,
                               'pins': [(87, 81), (89, 83)],
                               'type': 'MEDIUM'},
                'NET_338': {   'length': 3,
                               'pins': [(92, 81), (93, 83)],
                               'type': 'MEDIUM'},
                'NET_339': {   'length': 2,
                               'pins': [(95, 82), (96, 83)],
                               'type': 'MEDIUM'},
                'NET_34': {   'length': 4,
                              'pins': [(70, 7), (73, 8)],
                              'type': 'MEDIUM'},
                'NET_340': {   'length': 4,
                               'pins': [(0, 87), (3, 88)],
                               'type': 'MEDIUM'},
                'NET_341': {   'length': 4,
                               'pins': [(7, 85), (8, 88)],
                               'type': 'MEDIUM'},
                'NET_342': {   'length': 2,
                               'pins': [(12, 86), (13, 87)],
                               'type': 'MEDIUM'},
                'NET_343': {   'length': 3,
                               'pins': [(17, 85), (18, 87)],
                               'type': 'MEDIUM'},
                'NET_344': {   'length': 5,
                               'pins': [(21, 85), (23, 88)],
                               'type': 'MEDIUM'},
                'NET_345': {   'length': 4,
                               'pins': [(28, 86), (29, 89)],
                               'type': 'MEDIUM'},
                'NET_346': {   'length': 3,
                               'pins': [(32, 87), (33, 89)],
                               'type': 'MEDIUM'},
                'NET_347': {   'length': 4,
                               'pins': [(35, 86), (38, 87)],
                               'type': 'MEDIUM'},
                'NET_348': {   'length': 5,
                               'pins': [(40, 86), (43, 88)],
                               'type': 'MEDIUM'},
                'NET_349': {   'length': 3,
                               'pins': [(48, 85), (49, 87)],
                               'type': 'MEDIUM'},
                'NET_35': {   'length': 3,
                              'pins': [(75, 5), (77, 6)],
                              'type': 'MEDIUM'},
                'NET_350': {   'length': 4,
                               'pins': [(52, 87), (54, 89)],
                               'type': 'MEDIUM'},
                'NET_351': {   'length': 4,
                               'pins': [(57, 85), (58, 88)],
                               'type': 'MEDIUM'},
                'NET_352': {   'length': 5,
                               'pins': [(61, 85), (63, 88)],
                               'type': 'MEDIUM'},
                'NET_353': {   'length': 3,
                               'pins': [(66, 86), (68, 87)],
                               'type': 'MEDIUM'},
                'NET_354': {   'length': 3,
                               'pins': [(71, 87), (73, 88)],
                               'type': 'MEDIUM'},
                'NET_355': {   'length': 4,
                               'pins': [(75, 85), (78, 86)],
                               'type': 'MEDIUM'},
                'NET_356': {   'length': 3,
                               'pins': [(81, 86), (83, 87)],
                               'type': 'MEDIUM'},
                'NET_357': {   'length': 5,
                               'pins': [(85, 86), (88, 88)],
                               'type': 'MEDIUM'},
                'NET_358': {   'length': 2,
                               'pins': [(90, 85), (91, 86)],
                               'type': 'MEDIUM'},
                'NET_359': {   'length': 2,
                               'pins': [(96, 88), (97, 89)],
                               'type': 'MEDIUM'},
                'NET_36': {   'length': 3,
                              'pins': [(82, 7), (84, 8)],
                              'type': 'MEDIUM'},
                'NET_360': {   'length': 2,
                               'pins': [(2, 92), (3, 93)],
                               'type': 'MEDIUM'},
                'NET_361': {   'length': 2,
                               'pins': [(7, 90), (8, 91)],
                               'type': 'MEDIUM'},
                'NET_362': {   'length': 2,
                               'pins': [(12, 90), (13, 91)],
                               'type': 'MEDIUM'},
                'NET_363': {   'length': 2,
                               'pins': [(16, 92), (17, 93)],
                               'type': 'MEDIUM'},
                'NET_364': {   'length': 2,
                               'pins': [(23, 92), (24, 93)],
                               'type': 'MEDIUM'},
                'NET_365': {   'length': 3,
                               'pins': [(28, 91), (29, 93)],
                               'type': 'MEDIUM'},
                'NET_366': {   'length': 5,
                               'pins': [(31, 90), (33, 93)],
                               'type': 'MEDIUM'},
                'NET_367': {   'length': 2,
                               'pins': [(38, 93), (39, 94)],
                               'type': 'MEDIUM'},
                'NET_368': {   'length': 4,
                               'pins': [(42, 90), (43, 93)],
                               'type': 'MEDIUM'},
                'NET_369': {   'length': 2,
                               'pins': [(47, 91), (48, 92)],
                               'type': 'MEDIUM'},
                'NET_37': {   'length': 4,
                              'pins': [(87, 5), (88, 8)],
                              'type': 'MEDIUM'},
                'NET_370': {   'length': 4,
                               'pins': [(53, 91), (54, 94)],
                               'type': 'MEDIUM'},
                'NET_371': {   'length': 5,
                               'pins': [(55, 92), (58, 94)],
                               'type': 'MEDIUM'},
                'NET_372': {   'length': 2,
                               'pins': [(63, 90), (64, 91)],
                               'type': 'MEDIUM'},
                'NET_373': {   'length': 4,
                               'pins': [(65, 91), (66, 94)],
                               'type': 'MEDIUM'},
                'NET_374': {   'length': 5,
                               'pins': [(70, 93), (74, 94)],
                               'type': 'MEDIUM'},
                'NET_375': {   'length': 3,
                               'pins': [(78, 92), (79, 94)],
                               'type': 'MEDIUM'},
                'NET_376': {   'length': 3,
                               'pins': [(82, 92), (84, 93)],
                               'type': 'MEDIUM'},
                'NET_377': {   'length': 2,
                               'pins': [(87, 92), (88, 93)],
                               'type': 'MEDIUM'},
                'NET_378': {   'length': 2,
                               'pins': [(92, 92), (93, 93)],
                               'type': 'MEDIUM'},
                'NET_379': {   'length': 3,
                               'pins': [(98, 90), (99, 92)],
                               'type': 'MEDIUM'},
                'NET_38': {   'length': 3,
                              'pins': [(92, 5), (93, 7)],
                              'type': 'MEDIUM'},
                'NET_380': {   'length': 4,
                               'pins': [(2, 95), (3, 98)],
                               'type': 'MEDIUM'},
                'NET_381': {   'length': 5,
                               'pins': [(7, 96), (9, 99)],
                               'type': 'MEDIUM'},
                'NET_382': {   'length': 2,
                               'pins': [(13, 97), (14, 98)],
                               'type': 'MEDIUM'},
                'NET_383': {   'length': 3,
                               'pins': [(18, 97), (19, 99)],
                               'type': 'MEDIUM'},
                'NET_384': {   'length': 3,
                               'pins': [(21, 96), (22, 98)],
                               'type': 'MEDIUM'},
                'NET_385': {   'length': 4,
                               'pins': [(27, 96), (29, 98)],
                               'type': 'MEDIUM'},
                'NET_386': {   'length': 2,
                               'pins': [(30, 95), (31, 96)],
                               'type': 'MEDIUM'},
                'NET_387': {   'length': 4,
                               'pins': [(36, 96), (37, 99)],
                               'type': 'MEDIUM'},
                'NET_388': {   'length': 2,
                               'pins': [(42, 97), (43, 98)],
                               'type': 'MEDIUM'},
                'NET_389': {   'length': 2,
                               'pins': [(46, 97), (47, 98)],
                               'type': 'MEDIUM'},
                'NET_39': {   'length': 4,
                              'pins': [(96, 6), (99, 7)],
                              'type': 'MEDIUM'},
                'NET_390': {   'length': 2,
                               'pins': [(52, 96), (53, 97)],
                               'type': 'MEDIUM'},
                'NET_391': {   'length': 2,
                               'pins': [(57, 97), (58, 98)],
                               'type': 'MEDIUM'},
                'NET_392': {   'length': 3,
                               'pins': [(63, 97), (64, 99)],
                               'type': 'MEDIUM'},
                'NET_393': {   'length': 3,
                               'pins': [(66, 95), (68, 96)],
                               'type': 'MEDIUM'},
                'NET_394': {   'length': 3,
                               'pins': [(70, 96), (72, 97)],
                               'type': 'MEDIUM'},
                'NET_395': {   'length': 2,
                               'pins': [(78, 96), (79, 97)],
                               'type': 'MEDIUM'},
                'NET_396': {   'length': 2,
                               'pins': [(82, 97), (83, 98)],
                               'type': 'MEDIUM'},
                'NET_397': {   'length': 3,
                               'pins': [(86, 97), (88, 98)],
                               'type': 'MEDIUM'},
                'NET_398': {   'length': 2,
                               'pins': [(92, 95), (93, 96)],
                               'type': 'MEDIUM'},
                'NET_399': {   'length': 2,
                               'pins': [(97, 95), (98, 96)],
                               'type': 'MEDIUM'},
                'NET_4': {   'length': 3,
                             'pins': [(20, 2), (21, 4)],
                             'type': 'MEDIUM'},
                'NET_40': {   'length': 2,
                              'pins': [(3, 10), (4, 11)],
                              'type': 'MEDIUM'},
                'NET_41': {   'length': 3,
                              'pins': [(5, 12), (7, 13)],
                              'type': 'MEDIUM'},
                'NET_42': {   'length': 3,
                              'pins': [(10, 10), (12, 11)],
                              'type': 'MEDIUM'},
                'NET_43': {   'length': 4,
                              'pins': [(15, 11), (18, 12)],
                              'type': 'MEDIUM'},
                'NET_44': {   'length': 4,
                              'pins': [(21, 10), (22, 13)],
                              'type': 'MEDIUM'},
                'NET_45': {   'length': 5,
                              'pins': [(26, 11), (29, 13)],
                              'type': 'MEDIUM'},
                'NET_46': {   'length': 2,
                              'pins': [(32, 12), (33, 13)],
                              'type': 'MEDIUM'},
                'NET_47': {   'length': 3,
                              'pins': [(35, 11), (36, 13)],
                              'type': 'MEDIUM'},
                'NET_48': {   'length': 4,
                              'pins': [(41, 12), (44, 13)],
                              'type': 'MEDIUM'},
                'NET_49': {   'length': 2,
                              'pins': [(46, 12), (47, 13)],
                              'type': 'MEDIUM'},
                'NET_5': {   'length': 2,
                             'pins': [(25, 2), (26, 3)],
                             'type': 'MEDIUM'},
                'NET_50': {   'length': 4,
                              'pins': [(50, 10), (52, 12)],
                              'type': 'MEDIUM'},
                'NET_51': {   'length': 3,
                              'pins': [(57, 11), (58, 13)],
                              'type': 'MEDIUM'},
                'NET_52': {   'length': 3,
                              'pins': [(63, 11), (64, 13)],
                              'type': 'MEDIUM'},
                'NET_53': {   'length': 3,
                              'pins': [(67, 11), (68, 13)],
                              'type': 'MEDIUM'},
                'NET_54': {   'length': 2,
                              'pins': [(71, 12), (72, 13)],
                              'type': 'MEDIUM'},
                'NET_55': {   'length': 2,
                              'pins': [(77, 10), (78, 11)],
                              'type': 'MEDIUM'},
                'NET_56': {   'length': 4,
                              'pins': [(82, 11), (84, 13)],
                              'type': 'MEDIUM'},
                'NET_57': {   'length': 4,
                              'pins': [(86, 12), (89, 13)],
                              'type': 'MEDIUM'},
                'NET_58': {   'length': 4,
                              'pins': [(91, 11), (93, 13)],
                              'type': 'MEDIUM'},
                'NET_59': {   'length': 5,
                              'pins': [(96, 10), (98, 13)],
                              'type': 'MEDIUM'},
                'NET_6': {   'length': 5,
                             'pins': [(32, 1), (34, 4)],
                             'type': 'MEDIUM'},
                'NET_60': {   'length': 5,
                              'pins': [(1, 16), (4, 18)],
                              'type': 'MEDIUM'},
                'NET_61': {   'length': 3,
                              'pins': [(7, 16), (8, 18)],
                              'type': 'MEDIUM'},
                'NET_62': {   'length': 2,
                              'pins': [(10, 16), (11, 17)],
                              'type': 'MEDIUM'},
                'NET_63': {   'length': 4,
                              'pins': [(16, 17), (19, 18)],
                              'type': 'MEDIUM'},
                'NET_64': {   'length': 2,
                              'pins': [(23, 15), (24, 16)],
                              'type': 'MEDIUM'},
                'NET_65': {   'length': 5,
                              'pins': [(26, 15), (28, 18)],
                              'type': 'MEDIUM'},
                'NET_66': {   'length': 3,
                              'pins': [(32, 15), (33, 17)],
                              'type': 'MEDIUM'},
                'NET_67': {   'length': 2,
                              'pins': [(35, 17), (36, 18)],
                              'type': 'MEDIUM'},
                'NET_68': {   'length': 3,
                              'pins': [(42, 15), (43, 17)],
                              'type': 'MEDIUM'},
                'NET_69': {   'length': 3,
                              'pins': [(45, 15), (47, 16)],
                              'type': 'MEDIUM'},
                'NET_7': {   'length': 3,
                             'pins': [(35, 3), (37, 4)],
                             'type': 'MEDIUM'},
                'NET_70': {   'length': 3,
                              'pins': [(52, 16), (54, 17)],
                              'type': 'MEDIUM'},
                'NET_71': {   'length': 5,
                              'pins': [(56, 16), (58, 19)],
                              'type': 'MEDIUM'},
                'NET_72': {   'length': 2,
                              'pins': [(60, 17), (61, 18)],
                              'type': 'MEDIUM'},
                'NET_73': {   'length': 2,
                              'pins': [(65, 17), (66, 18)],
                              'type': 'MEDIUM'},
                'NET_74': {   'length': 2,
                              'pins': [(71, 17), (72, 18)],
                              'type': 'MEDIUM'},
                'NET_75': {   'length': 3,
                              'pins': [(75, 17), (76, 19)],
                              'type': 'MEDIUM'},
                'NET_76': {   'length': 4,
                              'pins': [(80, 15), (82, 17)],
                              'type': 'MEDIUM'},
                'NET_77': {   'length': 6,
                              'pins': [(86, 15), (89, 18)],
                              'type': 'MEDIUM'},
                'NET_78': {   'length': 4,
                              'pins': [(93, 15), (94, 18)],
                              'type': 'MEDIUM'},
                'NET_79': {   'length': 5,
                              'pins': [(97, 15), (98, 19)],
                              'type': 'MEDIUM'},
                'NET_8': {   'length': 4,
                             'pins': [(42, 0), (43, 3)],
                             'type': 'MEDIUM'},
                'NET_80': {   'length': 5,
                              'pins': [(0, 20), (3, 22)],
                              'type': 'MEDIUM'},
                'NET_81': {   'length': 2,
                              'pins': [(8, 23), (9, 24)],
                              'type': 'MEDIUM'},
                'NET_82': {   'length': 4,
                              'pins': [(12, 20), (13, 23)],
                              'type': 'MEDIUM'},
                'NET_83': {   'length': 5,
                              'pins': [(15, 22), (19, 23)],
                              'type': 'MEDIUM'},
                'NET_84': {   'length': 2,
                              'pins': [(22, 21), (23, 22)],
                              'type': 'MEDIUM'},
                'NET_85': {   'length': 2,
                              'pins': [(27, 22), (28, 23)],
                              'type': 'MEDIUM'},
                'NET_86': {   'length': 4,
                              'pins': [(30, 22), (33, 23)],
                              'type': 'MEDIUM'},
                'NET_87': {   'length': 4,
                              'pins': [(35, 21), (38, 22)],
                              'type': 'MEDIUM'},
                'NET_88': {   'length': 4,
                              'pins': [(41, 20), (42, 23)],
                              'type': 'MEDIUM'},
                'NET_89': {   'length': 4,
                              'pins': [(45, 22), (48, 23)],
                              'type': 'MEDIUM'},
                'NET_9': {   'length': 2,
                             'pins': [(46, 2), (47, 3)],
                             'type': 'MEDIUM'},
                'NET_90': {   'length': 6,
                              'pins': [(50, 22), (54, 24)],
                              'type': 'MEDIUM'},
                'NET_91': {   'length': 4,
                              'pins': [(57, 20), (58, 23)],
                              'type': 'MEDIUM'},
                'NET_92': {   'length': 2,
                              'pins': [(60, 20), (61, 21)],
                              'type': 'MEDIUM'},
                'NET_93': {   'length': 3,
                              'pins': [(67, 20), (68, 22)],
                              'type': 'MEDIUM'},
                'NET_94': {   'length': 4,
                              'pins': [(72, 22), (74, 24)],
                              'type': 'MEDIUM'},
                'NET_95': {   'length': 4,
                              'pins': [(76, 21), (78, 23)],
                              'type': 'MEDIUM'},
                'NET_96': {   'length': 4,
                              'pins': [(82, 21), (83, 24)],
                              'type': 'MEDIUM'},
                'NET_97': {   'length': 3,
                              'pins': [(88, 22), (89, 24)],
                              'type': 'MEDIUM'},
                'NET_98': {   'length': 2,
                              'pins': [(91, 23), (92, 24)],
                              'type': 'MEDIUM'},
                'NET_99': {   'length': 2,
                              'pins': [(97, 22), (98, 23)],
                              'type': 'MEDIUM'}}}
